<?php
/**
 * Definició dels continguts gestionables des del panell d'administració.
 * El controlador genèric (CrudController) crea els llistats i els formularis
 * automàticament a partir d'aquesta configuració.
 */
return [
    'patrocinadors' => [
        'table' => 'sponsors',
        'title' => 'Patrocinadors',
        'singular' => 'patrocinador',
        'icon' => 'heart',
        'description' => 'Logotips que apareixen a la portada i al peu de pàgina.',
        'order' => 'tier ASC, sort_order ASC, id ASC',
        'search' => ['name'],
        'columns' => ['logo' => 'Logotip', 'name' => 'Nom', 'tier' => 'Tipus', 'sort_order' => 'Ordre', 'active' => 'Actiu'],
        'fields' => [
            'name' => ['label' => 'Nom', 'type' => 'text', 'rules' => 'required|max:150'],
            'logo' => ['label' => 'Logotip', 'type' => 'image', 'folder' => 'sponsors', 'max_width' => 800, 'help' => 'PNG o SVG amb fons transparent.'],
            'url' => ['label' => 'Web', 'type' => 'url', 'placeholder' => 'https://'],
            'tier' => ['label' => 'Tipus', 'type' => 'select', 'default' => 'collaborador', 'options' => [
                'institucional' => 'Institucional',
                'principal' => 'Patrocinador principal',
                'collaborador' => 'Col·laborador',
                'mitjans' => 'Mitjans i altres',
            ]],
            'description' => ['label' => 'Descripció curta', 'type' => 'text', 'rules' => 'max:255'],
            'sort_order' => ['label' => 'Ordre', 'type' => 'number', 'default' => '0'],
            'active' => ['label' => 'Visible', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'recorreguts' => [
        'table' => 'courses',
        'title' => 'Recorreguts',
        'singular' => 'recorregut',
        'icon' => 'map',
        'description' => 'Circuits de la cursa amb el mapa de Wikiloc.',
        'order' => 'sort_order ASC, id ASC',
        'search' => ['name'],
        'columns' => ['name' => 'Nom', 'distance_m' => 'Distància', 'wikiloc_id' => 'Wikiloc', 'sort_order' => 'Ordre', 'active' => 'Actiu'],
        'fields' => [
            'name' => ['label' => 'Nom del recorregut', 'type' => 'text', 'rules' => 'required|max:150'],
            'slug' => ['label' => 'Adreça (slug)', 'type' => 'slug', 'source' => 'name', 'help' => 'S\'omple automàticament a partir del nom.'],
            'distance_m' => ['label' => 'Distància (metres)', 'type' => 'number', 'default' => '0'],
            'elevation_m' => ['label' => 'Desnivell positiu (metres)', 'type' => 'number'],
            'surface' => ['label' => 'Tipus de terreny', 'type' => 'text', 'placeholder' => 'Camins de vinya i asfalt'],
            'description' => ['label' => 'Descripció', 'type' => 'html', 'rows' => 5],
            'wikiloc_id' => ['label' => 'Identificador de Wikiloc', 'type' => 'text', 'help' => 'Número de la ruta (p. ex. 123456789). Si enganxeu l\'URL complet s\'extreu automàticament.'],
            'wikiloc_url' => ['label' => 'URL de Wikiloc', 'type' => 'url', 'placeholder' => 'https://ca.wikiloc.com/rutes-senderisme/...'],
            'gpx_file' => ['label' => 'Fitxer GPX', 'type' => 'file', 'folder' => 'documents', 'accept' => '.gpx'],
            'image' => ['label' => 'Imatge', 'type' => 'image', 'folder' => 'media', 'max_width' => 1400],
            'color' => ['label' => 'Color identificatiu', 'type' => 'color', 'default' => '#2f6b3c'],
            'sort_order' => ['label' => 'Ordre', 'type' => 'number', 'default' => '0'],
            'active' => ['label' => 'Visible', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'categories' => [
        'table' => 'categories',
        'title' => 'Categories',
        'singular' => 'categoria',
        'icon' => 'users',
        'description' => 'Categories per edat amb horari de sortida i recorregut.',
        'order' => 'sort_order ASC, id ASC',
        'search' => ['name', 'code'],
        'columns' => ['name' => 'Categoria', 'years' => 'Anys', 'start_time' => 'Sortida', 'distance_label' => 'Distància', 'active' => 'Activa'],
        'fields' => [
            'name' => ['label' => 'Nom', 'type' => 'text', 'rules' => 'required|max:120', 'placeholder' => 'Benjamí'],
            'code' => ['label' => 'Codi', 'type' => 'text', 'placeholder' => 'BEN', 'rules' => 'max:40'],
            'year_from' => ['label' => 'Any de naixement (des de)', 'type' => 'number'],
            'year_to' => ['label' => 'Any de naixement (fins a)', 'type' => 'number'],
            'gender' => ['label' => 'Gènere', 'type' => 'select', 'default' => 'mixt', 'options' => [
                'mixt' => 'Mixta', 'femeni' => 'Femenina', 'masculi' => 'Masculina',
            ]],
            'start_time' => ['label' => 'Hora de sortida', 'type' => 'time'],
            'distance_label' => ['label' => 'Distància', 'type' => 'text', 'placeholder' => '600 m'],
            'course_id' => ['label' => 'Recorregut', 'type' => 'relation', 'relation' => ['table' => 'courses', 'label' => 'name'], 'empty' => 'Sense assignar'],
            'prizes' => ['label' => 'Premis de la categoria', 'type' => 'textarea', 'rows' => 3, 'placeholder' => 'Medalla als tres primers classificats'],
            'notes' => ['label' => 'Observacions', 'type' => 'textarea', 'rows' => 2],
            'sort_order' => ['label' => 'Ordre', 'type' => 'number', 'default' => '0'],
            'active' => ['label' => 'Visible', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'premis' => [
        'table' => 'prizes',
        'title' => 'Premis',
        'singular' => 'premi',
        'icon' => 'trophy',
        'description' => 'Premis generals, trofeus i obsequis.',
        'order' => 'sort_order ASC, id ASC',
        'search' => ['title'],
        'columns' => ['title' => 'Premi', 'sort_order' => 'Ordre', 'active' => 'Actiu'],
        'fields' => [
            'title' => ['label' => 'Títol', 'type' => 'text', 'rules' => 'required|max:150'],
            'description' => ['label' => 'Descripció', 'type' => 'html', 'rows' => 4],
            'icon' => ['label' => 'Icona', 'type' => 'icon', 'default' => 'trophy'],
            'sort_order' => ['label' => 'Ordre', 'type' => 'number', 'default' => '0'],
            'active' => ['label' => 'Visible', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'programa' => [
        'table' => 'schedule_items',
        'title' => 'Programa',
        'singular' => 'acte del programa',
        'icon' => 'clock',
        'description' => 'Horaris de la jornada.',
        'order' => 'sort_order ASC, id ASC',
        'search' => ['title'],
        'columns' => ['time_label' => 'Hora', 'title' => 'Acte', 'sort_order' => 'Ordre', 'active' => 'Actiu'],
        'fields' => [
            'time_label' => ['label' => 'Hora', 'type' => 'text', 'placeholder' => '09:30'],
            'title' => ['label' => 'Acte', 'type' => 'text', 'rules' => 'required|max:150'],
            'description' => ['label' => 'Detall', 'type' => 'text', 'rules' => 'max:400'],
            'sort_order' => ['label' => 'Ordre', 'type' => 'number', 'default' => '0'],
            'active' => ['label' => 'Visible', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'destacats' => [
        'table' => 'info_blocks',
        'title' => 'Blocs destacats',
        'singular' => 'bloc destacat',
        'icon' => 'info',
        'description' => 'Targetes d\'informació de la portada (aparcament, avituallament, dorsals...).',
        'order' => 'sort_order ASC, id ASC',
        'search' => ['title'],
        'columns' => ['icon' => 'Icona', 'title' => 'Títol', 'sort_order' => 'Ordre', 'active' => 'Actiu'],
        'fields' => [
            'icon' => ['label' => 'Icona', 'type' => 'icon', 'default' => 'info'],
            'title' => ['label' => 'Títol', 'type' => 'text', 'rules' => 'required|max:150'],
            'body' => ['label' => 'Text', 'type' => 'html', 'rows' => 4],
            'sort_order' => ['label' => 'Ordre', 'type' => 'number', 'default' => '0'],
            'active' => ['label' => 'Visible', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'preguntes' => [
        'table' => 'faqs',
        'title' => 'Preguntes freqüents',
        'singular' => 'pregunta',
        'icon' => 'help',
        'description' => 'Dubtes habituals que es mostren a la portada.',
        'order' => 'sort_order ASC, id ASC',
        'search' => ['question'],
        'columns' => ['question' => 'Pregunta', 'sort_order' => 'Ordre', 'active' => 'Activa'],
        'fields' => [
            'question' => ['label' => 'Pregunta', 'type' => 'text', 'rules' => 'required|max:255'],
            'answer' => ['label' => 'Resposta', 'type' => 'html', 'rows' => 4],
            'sort_order' => ['label' => 'Ordre', 'type' => 'number', 'default' => '0'],
            'active' => ['label' => 'Visible', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'galeria' => [
        'table' => 'gallery',
        'title' => 'Galeria',
        'singular' => 'imatge',
        'icon' => 'image',
        'description' => 'Fotografies d\'edicions anteriors.',
        'order' => 'sort_order ASC, id ASC',
        'search' => ['caption'],
        'columns' => ['file' => 'Imatge', 'caption' => 'Peu de foto', 'sort_order' => 'Ordre', 'active' => 'Visible'],
        'fields' => [
            'file' => ['label' => 'Imatge', 'type' => 'image', 'folder' => 'media', 'max_width' => 1600, 'rules' => 'required'],
            'caption' => ['label' => 'Peu de foto', 'type' => 'text', 'rules' => 'max:200'],
            'sort_order' => ['label' => 'Ordre', 'type' => 'number', 'default' => '0'],
            'active' => ['label' => 'Visible', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'documents' => [
        'table' => 'documents',
        'title' => 'Documents',
        'singular' => 'document',
        'icon' => 'file',
        'description' => 'Bases de la cursa, autoritzacions i altres PDF.',
        'order' => 'sort_order ASC, id ASC',
        'search' => ['title'],
        'columns' => ['title' => 'Document', 'file' => 'Fitxer', 'sort_order' => 'Ordre', 'active' => 'Visible'],
        'fields' => [
            'title' => ['label' => 'Títol', 'type' => 'text', 'rules' => 'required|max:150'],
            'file' => ['label' => 'Fitxer PDF', 'type' => 'file', 'folder' => 'documents', 'accept' => '.pdf', 'rules' => 'required'],
            'description' => ['label' => 'Descripció', 'type' => 'text', 'rules' => 'max:255'],
            'sort_order' => ['label' => 'Ordre', 'type' => 'number', 'default' => '0'],
            'active' => ['label' => 'Visible', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'tipus-tiquet' => [
        'table' => 'ticket_types',
        'title' => 'Tipus de tiquet',
        'singular' => 'tipus de tiquet',
        'icon' => 'ticket',
        'description' => 'Productes del punt de recàrrega que es posen a la venda.',
        'order' => 'sort_order ASC, id ASC',
        'search' => ['name'],
        'columns' => ['name' => 'Tiquet', 'price_cents' => 'Preu', 'stock' => 'Existències', 'sold' => 'Venuts', 'active' => 'A la venda'],
        'fields' => [
            'name' => ['label' => 'Nom', 'type' => 'text', 'rules' => 'required|max:150', 'placeholder' => 'Esmorzar complet'],
            'description' => ['label' => 'Descripció', 'type' => 'textarea', 'rows' => 3, 'rules' => 'max:400', 'placeholder' => 'Entrepà, beguda i fruita'],
            'price_cents' => ['label' => 'Preu', 'type' => 'money', 'default' => '0', 'rules' => 'required'],
            'stock' => ['label' => 'Existències', 'type' => 'number', 'help' => 'Deixeu-ho buit per no limitar-les.'],
            'max_per_order' => ['label' => 'Màxim per comanda', 'type' => 'number', 'default' => '10'],
            'image' => ['label' => 'Imatge', 'type' => 'image', 'folder' => 'media', 'max_width' => 900],
            'sort_order' => ['label' => 'Ordre', 'type' => 'number', 'default' => '0'],
            'active' => ['label' => 'A la venda', 'type' => 'bool', 'default' => '1'],
        ],
    ],
];
