<?php
/**
 * Esquema dels textos i opcions configurables des del panell d'administració.
 * Els formularis del panell es generen automàticament a partir d'aquest fitxer.
 *
 * Tipus disponibles: text, textarea, html, email, url, tel, number, money, date,
 * time, color, coord, bool, select, image, file, password.
 */
return [
    'general' => [
        'title' => 'Dades de la cursa',
        'icon' => 'calendar',
        'description' => 'Informació bàsica de l\'esdeveniment que es mostra a tot el web.',
        'fields' => [
            'site_name' => ['label' => 'Nom del web', 'type' => 'text', 'default' => ''],
            'site_tagline' => ['label' => 'Lema', 'type' => 'text', 'default' => ''],
            'event_date' => ['label' => 'Data de la cursa', 'type' => 'date', 'default' => ''],
            'event_time' => ['label' => 'Hora d\'inici', 'type' => 'time', 'default' => '09:30'],
            'event_place' => ['label' => 'Lloc de sortida', 'type' => 'text', 'default' => ''],
            'event_address' => ['label' => 'Adreça', 'type' => 'text', 'default' => ''],
            'event_town' => ['label' => 'Població', 'type' => 'text', 'default' => ''],
            'map_lat' => ['label' => 'Latitud de la sortida', 'type' => 'coord', 'axis' => 'lat', 'default' => '',
                'help' => 'Punt exacte que marca el mapa. A OpenStreetMap, feu clic dret al lloc i trieu «Mostra l\'adreça»; també hi podeu enganxar un enllaç del mapa i se\'n treuen les coordenades.'],
            'map_lng' => ['label' => 'Longitud de la sortida', 'type' => 'coord', 'axis' => 'lng', 'default' => ''],
            'map_embed' => ['label' => 'Enllaç del mapa', 'type' => 'text', 'default' => '',
                'help' => 'Opcional. Si enganxeu un enllaç d\'OpenStreetMap o de Google Maps, el punt es treu de l\'enllaç. Si deixeu buides les coordenades i l\'enllaç, el mapa cercarà l\'adreça escrita aquí sobre.'],
            'organizer' => ['label' => 'Organitza', 'type' => 'text', 'default' => ''],
            'collaborators' => ['label' => 'Amb la col·laboració de', 'type' => 'text', 'default' => ''],
            'contact_email' => ['label' => 'Correu de contacte', 'type' => 'email', 'default' => ''],
            'contact_phone' => ['label' => 'Telèfon de contacte', 'type' => 'tel', 'default' => ''],
            'social_instagram' => ['label' => 'Instagram (URL)', 'type' => 'url', 'default' => ''],
            'social_facebook' => ['label' => 'Facebook (URL)', 'type' => 'url', 'default' => ''],
            'social_whatsapp' => ['label' => 'Grup de WhatsApp (URL)', 'type' => 'url', 'default' => ''],
            'pretty_urls' => ['label' => 'URLs amigables', 'type' => 'bool', 'default' => '1', 'help' => 'Desactiveu-ho només si el servidor no té la reescriptura d\'URL activada.'],
            'analytics_id' => ['label' => 'Identificador d\'analítica', 'type' => 'text', 'default' => '', 'help' => 'Opcional. Codi de Google Analytics 4 (G-XXXXXXX) o Matomo.'],
        ],
    ],

    'coming_soon' => [
        'title' => 'Web en preparació',
        'icon' => 'eye',
        'description' => 'Amaga el web al públic i mostra només un avís. Les persones amb sessió iniciada al panell continuen veient el web complet.',
        'fields' => [
            'coming_soon' => ['label' => 'Amagar el web al públic', 'type' => 'bool', 'default' => '0',
                'help' => 'Mentre estigui activat, qualsevol visitant veurà l\'avís «Aviat publicarem el web».'],
            'coming_soon_title' => ['label' => 'Títol de l\'avís', 'type' => 'text', 'default' => 'Aviat publicarem el web'],
            'coming_soon_text' => ['label' => 'Text de l\'avís', 'type' => 'html', 'rows' => 5,
                'default' => ''],
            'coming_soon_image' => ['label' => 'Imatge de fons', 'type' => 'image', 'default' => '',
                'help' => 'Opcional. Si no n\'hi ha cap, es fa servir la del banner de la portada o el fons il·lustrat de vinyes.'],
            'coming_soon_countdown' => ['label' => 'Mostrar la data i el compte enrere', 'type' => 'bool', 'default' => '1'],
            'coming_soon_contact' => ['label' => 'Mostrar el contacte i les xarxes', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'home' => [
        'title' => 'Portada',
        'icon' => 'home',
        'description' => 'Banner principal i textos de la pàgina d\'inici.',
        'fields' => [
            'hero_image' => ['label' => 'Imatge del banner', 'type' => 'image', 'default' => '', 'help' => 'Recomanat 1920×1080 px. Si no n\'hi ha cap, es mostra el fons il·lustrat de vinyes.'],
            'hero_badge' => ['label' => 'Etiqueta superior', 'type' => 'text', 'default' => ''],
            'hero_title' => ['label' => 'Títol del banner', 'type' => 'text', 'default' => ''],
            'hero_subtitle' => ['label' => 'Subtítol del banner', 'type' => 'textarea', 'rows' => 2, 'default' => ''],
            'hero_cta_label' => ['label' => 'Botó principal (text)', 'type' => 'text', 'default' => 'Inscripcions'],
            'hero_cta_url' => ['label' => 'Botó principal (enllaç)', 'type' => 'text', 'default' => '/inscripcio'],
            'hero_cta2_label' => ['label' => 'Botó secundari (text)', 'type' => 'text', 'default' => 'Categories i premis'],
            'hero_cta2_url' => ['label' => 'Botó secundari (enllaç)', 'type' => 'text', 'default' => '/categories-i-premis'],
            'countdown_enabled' => ['label' => 'Mostrar compte enrere', 'type' => 'bool', 'default' => '1'],
            'intro_title' => ['label' => 'Títol de la introducció', 'type' => 'text', 'default' => ''],
            'intro_text' => ['label' => 'Text de la introducció', 'type' => 'html', 'rows' => 6, 'default' => ''],
            'courses_title' => ['label' => 'Títol dels recorreguts', 'type' => 'text', 'default' => 'Els recorreguts'],
            'courses_intro' => ['label' => 'Text dels recorreguts', 'type' => 'textarea', 'rows' => 3, 'default' => 'Tots els circuits estan senyalitzats i controlats per voluntariat. Pots consultar-los al mapa de Wikiloc i descarregar el track per al teu rellotge.'],
            'schedule_title' => ['label' => 'Títol del programa', 'type' => 'text', 'default' => 'Programa de la jornada'],
            'schedule_intro' => ['label' => 'Text del programa', 'type' => 'textarea', 'rows' => 2, 'default' => 'Els horaris són orientatius i poden variar lleugerament segons la participació.'],
            'gallery_title' => ['label' => 'Títol de la galeria', 'type' => 'text', 'default' => 'Edicions anteriors'],
            'location_title' => ['label' => 'Títol de la ubicació', 'type' => 'text', 'default' => 'Com arribar-hi'],
            'location_text' => ['label' => 'Text de la ubicació', 'type' => 'textarea', 'rows' => 3, 'default' => ''],
            'sponsors_title' => ['label' => 'Títol dels patrocinadors', 'type' => 'text', 'default' => 'Amb el suport de'],
            'sponsors_intro' => ['label' => 'Text dels patrocinadors', 'type' => 'textarea', 'rows' => 2, 'default' => 'Gràcies a les entitats i empreses que fan possible aquesta cursa.'],
        ],
    ],

    'notices' => [
        'title' => 'Avisos',
        'icon' => 'info',
        'description' => 'La barra d\'avís de dalt de tot i la finestra emergent de la portada. Serveixen per a coses puntuals: un canvi d\'horari, un cartell, l\'últim dia per inscriure-s\'hi…',
        'fields' => [
            'topbar_enabled' => ['label' => 'Mostrar la barra d\'avís', 'type' => 'bool', 'default' => '0', 'section' => 'Barra d\'avís, a dalt de tot',
                'help' => 'Surt a dalt de tot, sobre el menú, a totes les pàgines del web.'],
            'topbar_text' => ['label' => 'Missatge de la barra', 'type' => 'text', 'default' => '', 'show_if' => 'topbar_enabled',
                'placeholder' => 'Les inscripcions es tanquen diumenge!',
                'help' => 'Si el deixeu buit, la barra no surt encara que estigui activada.'],
            'topbar_url' => ['label' => 'Enllaç de la barra', 'type' => 'text', 'default' => '', 'show_if' => 'topbar_enabled',
                'placeholder' => '/inscripcio',
                'help' => 'Opcional. Una adreça d\'aquest web (/inscripcio) o de fora (https://…), que s\'obre en una finestra nova.'],
            'topbar_link_label' => ['label' => 'Text de l\'enllaç', 'type' => 'text', 'default' => 'Més informació', 'show_if' => 'topbar_enabled',
                'help' => 'El que es llegeix al botó de la barra.'],
            'topbar_bg' => ['label' => 'Color de fons de la barra', 'type' => 'color', 'default' => '#c8552b', 'show_if' => 'topbar_enabled'],
            'topbar_color' => ['label' => 'Color del text de la barra', 'type' => 'color', 'default' => '#ffffff', 'show_if' => 'topbar_enabled'],
            'topbar_dismissible' => ['label' => 'Els visitants la poden tancar', 'type' => 'bool', 'default' => '1', 'show_if' => 'topbar_enabled',
                'help' => 'Amb una creu a la dreta. Un cop tancada no torna a sortir fins que canvieu el missatge o el visitant torni a obrir el navegador.'],

            'popup_enabled' => ['label' => 'Mostrar la finestra emergent a la portada', 'type' => 'bool', 'default' => '0', 'section' => 'Cartell emergent de la portada',
                'help' => 'Un cartell que surt damunt de la portada en obrir-la.'],
            'popup_image' => ['label' => 'Imatge del cartell', 'type' => 'image', 'default' => '', 'show_if' => 'popup_enabled',
                'help' => 'Sense imatge no surt res. Es veu sencera, sense retallar; va bé qualsevol format (JPG, PNG o WEBP).'],
            'popup_alt' => ['label' => 'Descripció de la imatge', 'type' => 'text', 'default' => '', 'show_if' => 'popup_enabled',
                'placeholder' => 'Cartell del Cros Escolar 2026',
                'help' => 'El que llegeix qui no pot veure la imatge. Val la pena escriure-la.'],
            'popup_url' => ['label' => 'Enllaç en clicar la imatge', 'type' => 'text', 'default' => '', 'show_if' => 'popup_enabled',
                'placeholder' => 'https://…',
                'help' => 'Opcional. S\'obre en una finestra nova. Sense enllaç, la imatge només es mostra.'],
            'popup_once' => ['label' => 'Ensenyar-lo un sol cop per visita', 'type' => 'bool', 'default' => '1', 'show_if' => 'popup_enabled',
                'help' => 'Recomanat: així qui torni a la portada durant la mateixa visita no se\'l torna a trobar.'],
        ],
    ],

    'tickets' => [
        'title' => 'Punt de recàrrega i tiquets',
        'icon' => 'ticket',
        'description' => 'El punt de recàrrega és el servei de bar de la cursa: on es recuperen forces en acabar. Aquí se\'n configuren la informació i els tiquets.',
        'fields' => [
            'tickets_public_mode' => ['label' => 'Què es mostra al web', 'type' => 'select', 'default' => 'info', 'options' => [
                'info' => 'Només informació (sense compra en línia)',
                'sale' => 'Informació i venda en línia amb targeta',
            ], 'help' => 'Amb «només informació» el web explica el punt de recàrrega i els preus, però no s\'hi pot comprar. La gestió de tiquets, comandes i validació continua al panell.'],
            'tickets_enabled' => ['label' => 'Venda en línia oberta', 'type' => 'bool', 'default' => '1',
                'help' => 'Només té efecte si heu triat la venda en línia.'],
            'tickets_title' => ['label' => 'Títol de la pàgina', 'type' => 'text', 'default' => 'Tiquets del punt de recàrrega'],
            'tickets_intro' => ['label' => 'Introducció', 'type' => 'html', 'rows' => 5, 'default' => '<p>En acabar les curses obrirem el punt de recàrrega: entrepans, beguda i fruita per recuperar l\'energia gastada corrent. Els tiquets es podran comprar a la carpa de l\'organització el mateix dia de la cursa.</p>'],
            'tickets_deadline' => ['label' => 'Data límit de venda', 'type' => 'date', 'default' => '', 'help' => 'Després d\'aquesta data la botiga es tanca automàticament.'],
            'tickets_max_per_order' => ['label' => 'Màxim d\'unitats per comanda', 'type' => 'number', 'default' => '20'],
            'tickets_info' => ['label' => 'Informació pràctica', 'type' => 'html', 'rows' => 4, 'default' => '<ul><li>Els tiquets es venen el mateix dia a la carpa de l\'organització.</li><li>Es poden pagar en efectiu o amb targeta.</li><li>Hi haurà opcions vegetarianes i sense gluten.</li></ul>'],
            'tickets_terms' => ['label' => 'Condicions de compra', 'type' => 'html', 'rows' => 4, 'default' => ''],
            'tickets_closed_text' => ['label' => 'Text quan la venda està tancada', 'type' => 'html', 'rows' => 3, 'default' => '<p>La venda anticipada de tiquets ja està tancada. El mateix dia de la cursa en podreu comprar a la carpa de l\'organització fins a exhaurir existències.</p>'],
            'tickets_success_text' => ['label' => 'Text de confirmació de compra', 'type' => 'html', 'rows' => 3, 'default' => '<p>Gràcies per col·laborar-hi! Rebràs els tiquets per correu electrònic. També els pots consultar sempre que vulguis des d\'aquesta pàgina.</p>'],
            'tickets_email_intro' => ['label' => 'Text del correu de confirmació', 'type' => 'textarea', 'rows' => 3, 'default' => 'Gràcies per comprar els tiquets del punt de recàrrega. Presenta aquest correu o el codi QR de cada tiquet el dia de la cursa.'],
        ],
    ],

    'categories' => [
        'title' => 'Categories i premis',
        'icon' => 'trophy',
        'description' => 'Textos de la pàgina de categories, horaris i premis.',
        'fields' => [
            'categories_title' => ['label' => 'Títol de la pàgina', 'type' => 'text', 'default' => 'Categories i premis'],
            'categories_intro' => ['label' => 'Introducció', 'type' => 'html', 'rows' => 4, 'default' => '<p>Hi ha una cursa per a cada edat, de les més petites fins a les d\'adults i famílies. Consulta la teva categoria, l\'hora de sortida i la distància del recorregut.</p>'],
            'categories_notes' => ['label' => 'Notes finals', 'type' => 'html', 'rows' => 4, 'default' => '<p>Totes les persones participants rebran un obsequi de record. Cal ser al lloc de sortida 10 minuts abans de l\'hora indicada.</p>'],
            'prizes_title' => ['label' => 'Títol dels premis', 'type' => 'text', 'default' => 'Premis'],
            'prizes_intro' => ['label' => 'Introducció dels premis', 'type' => 'textarea', 'rows' => 3, 'default' => 'El lliurament de premis es farà a la zona d\'arribada en acabar l\'última cursa.'],
            'prizes_local_label' => ['label' => 'Nom del premi local', 'type' => 'text', 'default' => 'Primer local',
                'help' => 'Premi per al primer classificat de l\'escola del poble dins de cada categoria. A cada categoria podeu decidir si el doneu, i el guanyador es marca a mà a Resultats.'],
            'prizes_local_school' => ['label' => 'Escola del poble', 'type' => 'text', 'default' => '',
                'help' => 'Serveix per assenyalar-vos al panell qui hi pot optar. El premi el marqueu vosaltres: el nom de l\'escola es pot haver escrit de mil maneres.'],
        ],
    ],

    'rules' => [
        'title' => 'Reglament',
        'icon' => 'file',
        'description' => 'Reglament de la cursa. Es publica en una pàgina pròpia i s\'ha d\'acceptar en inscriure\'s.',
        'fields' => [
            'rules_title' => ['label' => 'Títol de la pàgina', 'type' => 'text', 'default' => 'Reglament de la cursa'],
            'rules_text' => ['label' => 'Text del reglament', 'type' => 'html', 'rows' => 22, 'default' => '<h2>1. La cursa</h2><p>El {{cursa}} és una cursa popular de caràcter no competitiu, oberta a totes les edats, organitzada per l\'{{entitat}} a {{poble}}. Es fa el dia i a l\'hora anunciats al web, amb sortida i arribada al lloc que s\'hi indica.</p><h2>2. Qui hi pot participar</h2><p>Hi pot participar qualsevol persona, sigui o no del poble. Cada participant corre a la categoria que li correspon per any de naixement; l\'organització l\'assigna automàticament en fer la inscripció. Les persones menors d\'edat han de ser inscrites pel pare, la mare o qui en tingui la tutela legal.</p><h2>3. Inscripcions</h2><p>La inscripció és gratuïta i es fa pel web fins a la data de tancament que s\'hi indica. Cal emplenar un formulari per cada participant. Les dades s\'han de facilitar correctament: l\'any de naixement determina la categoria i una dada errònia pot deixar el resultat sense validesa.</p><p>Un cop tancades les inscripcions en línia, qui vulgui apuntar-s\'hi encara ho pot fer a la carpa de l\'organització el mateix dia, fins a 30 minuts abans de la sortida de la seva categoria, mentre hi hagi dorsals disponibles.</p><h2>4. Dorsals</h2><p>Cada participant rep un número de dorsal en inscriure\'s. El dorsal es recull el mateix dia al lloc de sortida i s\'ha de portar col·locat al pit, sencer i ben visible, durant tota la cursa. El dorsal és personal i intransferible: no es pot córrer amb el dorsal d\'una altra persona.</p><h2>5. Horaris i sortides</h2><p>Els horaris de cada categoria es publiquen al web i poden variar lleugerament segons la participació. Cal ser a la zona de sortida <strong>15 minuts abans</strong> de l\'hora prevista. Qui no hi sigui a l\'hora de la sortida pot sortir igualment, però ho farà darrere del grup.</p><h2>6. Recorregut</h2><p>Els recorreguts estan senyalitzats i controlats per persones voluntàries, a les quals cal fer cas en tot moment. S\'ha de seguir el recorregut marcat de principi a fi: escurçar-lo o sortir-ne comporta quedar fora de la classificació. Hi pot haver trams de camí, terra o carrer obert al trànsit controlat.</p><h2>7. Classificacions i premis</h2><p>L\'ordre d\'arribada de cada categoria es pren a meta. Els resultats es publiquen al web un cop acabada la jornada. Els premis de cada categoria es detallen a la pàgina de categories i premis, i es lliuren en acabar l\'última cursa. Cal ser-hi present per recollir-los.</p><h2>8. Acompanyants</h2><p>A les categories més petites s\'hi admet una persona acompanyant per infant, que ha de córrer per fora del grup i sense destorbar la resta. Les persones acompanyants no consten a la classificació. No es pot participar amb bicicleta, patins ni animals de companyia.</p><h2>9. Salut i seguretat</h2><p>Cada participant, o qui en tingui la tutela legal, declara que està en condicions físiques adequades per fer la cursa i hi participa sota la seva responsabilitat. Qui pateixi alguna afecció que calgui tenir en compte ho pot fer constar a les observacions del formulari d\'inscripció. Durant la jornada hi ha servei d\'assistència sanitària bàsica.</p><p>L\'organització pot retirar de la cursa qualsevol participant que, a criteri del personal sanitari o de l\'organització, no estigui en condicions de continuar.</p><h2>10. Canvis i suspensió</h2><p>L\'organització pot modificar els horaris, els recorreguts o qualsevol altre aspecte de la jornada, i també ajornar-la o suspendre-la, per motius de seguretat, meteorològics o de força major. Els canvis es comuniquen pel web i, si cal, per correu electrònic a les persones inscrites.</p><h2>11. Dades personals i imatges</h2><p>Les dades de la inscripció es tracten tal com s\'explica a la <a href="/privacitat">política de privacitat</a>. Durant la cursa es fan fotografies i vídeos de l\'activitat, que es poden publicar als canals de l\'organització només si s\'ha autoritzat expressament al formulari d\'inscripció.</p><h2>12. Acceptació</h2><p>Inscriure\'s a la cursa implica acceptar aquest reglament i les indicacions de l\'organització i del voluntariat. Qualsevol cas no previst aquí el resol l\'organització.</p>',
                'help' => 'Es publica a /reglament i s\'enllaça des del formulari d\'inscripció i del peu de pàgina. Admet els mateixos marcadors que els textos legals: {{entitat}}, {{cursa}}, {{poble}}, {{correu}}, {{telefon}} i {{web}}.'],
            'rules_consent' => ['label' => 'Demanar que s\'accepti en inscriure\'s', 'type' => 'bool', 'default' => '1',
                'help' => 'Afegeix una casella al formulari d\'inscripció. Si la desactiveu, la pàgina del reglament continua publicada però no es demana acceptar-lo.'],
            'rules_consent_label' => ['label' => 'Text de la casella', 'type' => 'text', 'default' => 'Accepto el reglament de la cursa',
                'show_if' => 'rules_consent',
                'help' => 'Al formulari, aquest text fa d\'enllaç al reglament.'],
        ],
    ],

    'registrations' => [
        'title' => 'Inscripcions',
        'icon' => 'users',
        'description' => 'Inscripció a les curses. Podeu tenir el formulari en línia actiu o mostrar només un text informatiu.',
        'fields' => [
            'registrations_enabled' => ['label' => 'Formulari d\'inscripció en línia actiu', 'type' => 'bool', 'default' => '1',
                'help' => 'Si el desactiveu, la pàgina d\'inscripció només mostrarà el text informatiu de més avall, sense cap formulari.'],
            'registrations_title' => ['label' => 'Títol de la pàgina', 'type' => 'text', 'default' => 'Inscripció a la cursa'],
            'registrations_intro' => ['label' => 'Introducció (només amb el formulari actiu)', 'type' => 'html', 'rows' => 4, 'default' => '<p>La inscripció és gratuïta i oberta a tothom qui vulgui participar. Empleneu un formulari per cada participant.</p>'],
            'registrations_aside' => ['label' => 'Mostrar el requadre de recordatoris', 'type' => 'bool', 'default' => '1',
                'help' => 'És el requadre que surt al costat del formulari, amb el que cal tenir present abans d\'inscriure\'s.'],
            'registrations_aside_title' => ['label' => 'Títol del requadre', 'type' => 'text', 'default' => 'Recorda', 'show_if' => 'registrations_aside'],
            'registrations_aside_text' => ['label' => 'Contingut del requadre', 'type' => 'html', 'rows' => 6, 'show_if' => 'registrations_aside',
                'default' => '<ul><li>Cal omplir un formulari per cada participant.</li><li>Els dorsals es recullen el mateix dia al lloc de sortida.</li><li>Arribeu 15 minuts abans de la vostra sortida.</li><li>El punt de recàrrega té tiquet a part: <a href="/punt-de-recarrega">mira-ho aquí</a>.</li></ul>'],
            'registrations_close_at' => ['label' => 'Data de tancament del formulari', 'type' => 'date', 'default' => '',
                'help' => 'Passada aquesta data el formulari es tanca sol i es mostra el text informatiu. Deixeu-ho buit per no posar-hi data límit.'],
            'registrations_closed_text' => ['label' => 'Text informatiu (sense formulari)', 'type' => 'html', 'rows' => 5, 'default' => '<p>Enguany les inscripcions no es fan per internet. El mateix dia de la cursa hi haurà inscripcions presencials a la carpa de l\'organització fins a 30 minuts abans de cada sortida.</p>', 'help' => 'És l\'únic que es veurà a la pàgina quan el formulari estigui desactivat o s\'hagi passat la data.'],
            'registrations_closed_link_label' => ['label' => 'Botó opcional: text', 'type' => 'text', 'default' => '', 'placeholder' => 'Descarregar el full d\'inscripció'],
            'registrations_closed_link_url' => ['label' => 'Botó opcional: enllaç', 'type' => 'text', 'default' => '', 'placeholder' => 'https://…  o  /punt-de-recarrega',
                'help' => 'Si ompliu els dos camps, sota el text hi apareixerà un botó (per exemple cap a un PDF o a un formulari extern).'],
            'registrations_confetti' => ['label' => 'Confeti en confirmar la inscripció', 'type' => 'bool', 'default' => '1',
                'help' => 'Un efecte de festa a la pàgina de confirmació. Qui tingui activat «reduir el moviment» al seu dispositiu no el veurà.'],
            'registrations_success_text' => ['label' => 'Text de confirmació', 'type' => 'html', 'rows' => 3, 'default' => '<p>Inscripció rebuda! Us hem enviat un correu de confirmació amb les dades. Ens veiem el dia de la cursa.</p>'],
            'registrations_payment' => ['label' => 'Cobrar la inscripció', 'type' => 'bool', 'default' => '0',
                'help' => 'Amb això actiu, qui s\'inscriu tria un tipus d\'inscripció i paga abans de quedar confirmat. Els tipus i els preus es posen a Continguts → Tipus d\'inscripció, i la passarel·la a Configuració → Cobraments.'],
            'registrations_payment_note' => ['label' => 'Què es diu sobre el pagament', 'type' => 'textarea', 'rows' => 2, 'show_if' => 'registrations_payment',
                'default' => 'La inscripció no queda confirmada fins que el pagament s\'hagi fet. Si el pagament falla, podeu tornar-ho a provar des de l\'enllaç del correu.'],
            'registrations_selfservice' => ['label' => '«Les meves inscripcions» actiu', 'type' => 'bool', 'default' => '1',
                'help' => 'Permet que les famílies entrin amb un codi que reben per correu per revisar i modificar les dades dels seus participants. Si ho desactiveu, la pàgina deixa d\'existir.'],
            'registrations_notify' => ['label' => 'Avisar per correu de cada inscripció', 'type' => 'bool', 'default' => '1'],
            'registrations_consent' => ['label' => 'Text del consentiment de dades', 'type' => 'textarea', 'rows' => 3, 'default' => 'Accepto que les dades facilitades s\'utilitzin únicament per gestionar la participació en aquesta cursa.'],
            'registrations_image_consent' => ['label' => 'Text del consentiment d\'imatge', 'type' => 'textarea', 'rows' => 3, 'default' => 'Autoritzo la publicació d\'imatges de l\'esdeveniment als canals de l\'organització.'],
        ],
    ],

    'bibs' => [
        'title' => 'Dorsals',
        'icon' => 'flag',
        'description' => 'Maqueta dels dorsals i on s\'hi col·loquen les dades de cada participant. Les posicions es mesuren en mil·límetres des de la cantonada superior esquerra.',
        'fields' => [
            'bib_public_download' => ['label' => 'Les famílies poden descarregar el dorsal', 'type' => 'bool', 'default' => '1',
                'help' => 'Si ho desactiveu, l\'enllaç per descarregar el dorsal desapareix del web, de «Les meves inscripcions» i dels correus de confirmació. Des del panell els podreu continuar imprimint.'],
            'bib_template' => ['label' => 'Maqueta del dorsal (PDF)', 'type' => 'file', 'folder' => 'documents', 'accept' => '.pdf', 'default' => '', 'help' => 'Pugeu el disseny en PDF. Si no n\'hi ha cap, els dorsals es generen sobre un fons blanc.'],
            'bib_template_page' => ['label' => 'Pàgina de la maqueta', 'type' => 'number', 'default' => '1', 'help' => 'Per si el PDF té més d\'una pàgina.'],
            'bib_orientation' => ['label' => 'Orientació del dorsal', 'type' => 'select', 'default' => 'auto',
                'options' => ['auto' => 'La mateixa que la maqueta', 'portrait' => 'Vertical', 'landscape' => 'Horitzontal'],
                'help' => 'Amb «la mateixa que la maqueta» el dorsal surt amb la mida i l\'orientació del PDF que heu pujat. Si en marqueu una altra, la maqueta es gira per omplir la pàgina: és el cas d\'un disseny apaïsat desat en un PDF vertical. Després de canviar-la, reviseu les posicions de més avall amb el botó «Dorsal de prova».'],
            'bib_template_rotate' => ['label' => 'Gir de la maqueta', 'type' => 'select', 'default' => '0',
                'options' => ['0' => 'Cap', '90' => '90° cap a l\'esquerra', '180' => 'Del revés (180°)', '270' => '90° cap a la dreta'],
                'help' => 'Només si la maqueta surt de costat o del revés: el gir s\'aplica abans de l\'orientació. Comproveu-ho amb el botó «Dorsal de prova».'],
            'bib_page_size' => ['label' => 'Mida quan no hi ha maqueta', 'type' => 'select', 'default' => 'a5', 'options' => ['a4' => 'A4 (210×297 mm)', 'a5' => 'A5 (148×210 mm)', 'a6' => 'A6 (105×148 mm)'],
                'help' => 'L\'orientació de més amunt també s\'hi aplica.'],
            'bib_two_per_sheet' => ['label' => 'Dos dorsals per full A4', 'type' => 'bool', 'default' => '0',
                'help' => 'En imprimir-los, cada full A4 vertical porta dos dorsals, un a dalt i un a baix, per gastar la meitat de paper. Només s\'aplica si el dorsal hi cap: un A5 apaïsat (210×148 mm) o més petit. Si és més gran, se\'n continua fent un per full.'],
            'bib_digits' => ['label' => 'Xifres del número de dorsal', 'type' => 'number', 'default' => '3', 'help' => 'Amb 3 xifres, el dorsal 1 es mostra com a 001.'],
            'bib_number_show' => ['label' => 'Mostrar el número', 'type' => 'bool', 'default' => '1'],
            'bib_number_x' => ['label' => 'El número: posició X (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '74'],
            'bib_number_y' => ['label' => 'El número: posició Y (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '120'],
            'bib_number_size' => ['label' => 'El número: mida de lletra (pt)', 'type' => 'number', 'step' => '0.5', 'default' => '90'],
            'bib_number_color' => ['label' => 'El número: color', 'type' => 'color', 'default' => '#12301c'],
            'bib_number_align' => ['label' => 'El número: alineació', 'type' => 'select', 'default' => 'center', 'options' => ['left' => 'Esquerra', 'center' => 'Centrat', 'right' => 'Dreta']],
            'bib_number_bold' => ['label' => 'El número: negreta', 'type' => 'bool', 'default' => '1'],
            'bib_name_show' => ['label' => 'Mostrar el nom', 'type' => 'bool', 'default' => '1'],
            'bib_name_first_only' => ['label' => 'Només el nom, sense cognoms', 'type' => 'bool', 'default' => '0',
                'show_if' => 'bib_name_show',
                'help' => 'Al dorsal hi surt «Laia» en lloc de «Laia Ferrer Miró». Va bé quan el dorsal és petit o quan es vol que s\'hi llegeixi de lluny.'],
            'bib_name_x' => ['label' => 'El nom: posició X (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '74'],
            'bib_name_y' => ['label' => 'El nom: posició Y (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '150'],
            'bib_name_size' => ['label' => 'El nom: mida de lletra (pt)', 'type' => 'number', 'step' => '0.5', 'default' => '18'],
            'bib_name_color' => ['label' => 'El nom: color', 'type' => 'color', 'default' => '#12301c'],
            'bib_name_align' => ['label' => 'El nom: alineació', 'type' => 'select', 'default' => 'center', 'options' => ['left' => 'Esquerra', 'center' => 'Centrat', 'right' => 'Dreta']],
            'bib_name_bold' => ['label' => 'El nom: negreta', 'type' => 'bool', 'default' => '0'],
            'bib_category_show' => ['label' => 'Mostrar la categoria', 'type' => 'bool', 'default' => '1'],
            'bib_category_x' => ['label' => 'La categoria: posició X (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '74'],
            'bib_category_y' => ['label' => 'La categoria: posició Y (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '163'],
            'bib_category_size' => ['label' => 'La categoria: mida de lletra (pt)', 'type' => 'number', 'step' => '0.5', 'default' => '12'],
            'bib_category_color' => ['label' => 'La categoria: color', 'type' => 'color', 'default' => '#4a5b50'],
            'bib_category_align' => ['label' => 'La categoria: alineació', 'type' => 'select', 'default' => 'center', 'options' => ['left' => 'Esquerra', 'center' => 'Centrat', 'right' => 'Dreta']],
            'bib_category_bold' => ['label' => 'La categoria: negreta', 'type' => 'bool', 'default' => '0'],
            'bib_school_show' => ['label' => 'Mostrar l\'escola', 'type' => 'bool', 'default' => '0',
                'help' => 'L\'escola o club que la família ha escrit a la inscripció. Ve desactivat: activeu-lo i col·loqueu-lo amb el botó «Dorsal de prova».'],
            'bib_school_x' => ['label' => 'L\'escola: posició X (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '74', 'show_if' => 'bib_school_show'],
            'bib_school_y' => ['label' => 'L\'escola: posició Y (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '176', 'show_if' => 'bib_school_show'],
            'bib_school_size' => ['label' => 'L\'escola: mida de lletra (pt)', 'type' => 'number', 'step' => '0.5', 'default' => '11', 'show_if' => 'bib_school_show'],
            'bib_school_color' => ['label' => 'L\'escola: color', 'type' => 'color', 'default' => '#4a5b50', 'show_if' => 'bib_school_show'],
            'bib_school_align' => ['label' => 'L\'escola: alineació', 'type' => 'select', 'default' => 'center', 'show_if' => 'bib_school_show',
                'options' => ['left' => 'Esquerra', 'center' => 'Centrat', 'right' => 'Dreta']],
            'bib_school_bold' => ['label' => 'L\'escola: negreta', 'type' => 'bool', 'default' => '0', 'show_if' => 'bib_school_show'],
        ],
    ],

    'results' => [
        'title' => 'Resultats',
        'icon' => 'trophy',
        'description' => 'Publicació dels resultats de la cursa al web.',
        'fields' => [
            'results_published' => ['label' => 'Publicar els resultats al web', 'type' => 'bool', 'default' => '0',
                'help' => 'Mentre no estigui activat, els visitants no hi tenen pàgina. Vós sí: amb la sessió '
                    . 'iniciada podeu obrir-la des de Resultats → Vista prèvia i comprovar com quedarà.'],
            'results_title' => ['label' => 'Títol de la pàgina', 'type' => 'text', 'default' => 'Resultats de la cursa'],
            'results_intro' => ['label' => 'Introducció', 'type' => 'html', 'rows' => 4, 'default' => ''],
            'results_note' => ['label' => 'Nota final', 'type' => 'html', 'rows' => 3, 'default' => '<p>Si detecteu cap errada a la classificació, escriviu-nos i la corregirem.</p>'],
            'results_show_bib' => ['label' => 'Mostrar el número de dorsal', 'type' => 'bool', 'default' => '1'],
            'results_public_pdf' => ['label' => 'Permetre descarregar els resultats en PDF', 'type' => 'bool', 'default' => '1'],
            'results_pdf_sponsors' => ['label' => 'Posar els logotips dels patrocinadors al peu del PDF', 'type' => 'bool', 'default' => '0',
                'help' => 'Hi surten tots els patrocinadors actius que tinguin logotip, en una sola línia i tots '
                    . 'a la mateixa alçada. Els fitxers han de ser PNG o JPEG.'],
        ],
    ],

    'payments' => [
        'title' => 'Cobraments',
        'icon' => 'card',
        'description' => 'Com es cobren les inscripcions i els tiquets. Només pot haver-hi una passarel·la activa: '
            . 'tenir-ne dues obertes alhora acaba amb mitja comptabilitat en un lloc i mitja en un altre.',
        'admin_only' => true,
        'fields' => [
            'payments_gateway' => ['label' => 'Passarel·la activa', 'type' => 'select', 'default' => '',
                'options' => ['' => 'Cap: no es cobra res en línia', 'stripe' => 'Stripe (targeta, Bizum i altres)',
                    'paypal' => 'PayPal', 'redsys' => 'Redsys (TPV del banc)'],
                'help' => 'En triar-ne una, hi apareixen les seves dades. Les que no s\'utilitzin es queden desades per si es torna enrere.'],

            'stripe_mode' => ['label' => 'Stripe: mode', 'type' => 'select', 'default' => 'test', 'show_if' => 'payments_gateway:stripe',
                'options' => ['test' => 'Proves (test)', 'live' => 'Producció (live)']],
            'stripe_pk_test' => ['label' => 'Stripe: clau pública de proves', 'type' => 'text', 'default' => '', 'placeholder' => 'pk_test_...', 'show_if' => 'payments_gateway:stripe'],
            'stripe_sk_test' => ['label' => 'Stripe: clau secreta de proves', 'type' => 'password', 'secret' => true, 'default' => '', 'placeholder' => 'sk_test_...', 'show_if' => 'payments_gateway:stripe'],
            'stripe_webhook_test' => ['label' => 'Stripe: secret del webhook (proves)', 'type' => 'password', 'secret' => true, 'default' => '', 'placeholder' => 'whsec_...', 'show_if' => 'payments_gateway:stripe'],
            'stripe_pk_live' => ['label' => 'Stripe: clau pública de producció', 'type' => 'text', 'default' => '', 'placeholder' => 'pk_live_...', 'show_if' => 'payments_gateway:stripe'],
            'stripe_sk_live' => ['label' => 'Stripe: clau secreta de producció', 'type' => 'password', 'secret' => true, 'default' => '', 'placeholder' => 'sk_live_...', 'show_if' => 'payments_gateway:stripe'],
            'stripe_webhook_live' => ['label' => 'Stripe: secret del webhook (producció)', 'type' => 'password', 'secret' => true, 'default' => '', 'placeholder' => 'whsec_...', 'show_if' => 'payments_gateway:stripe'],

            'paypal_mode' => ['label' => 'PayPal: mode', 'type' => 'select', 'default' => 'sandbox', 'show_if' => 'payments_gateway:paypal',
                'options' => ['sandbox' => 'Proves (sandbox)', 'live' => 'Producció (live)']],
            'paypal_client_id' => ['label' => 'PayPal: identificador del client', 'type' => 'text', 'default' => '', 'show_if' => 'payments_gateway:paypal'],
            'paypal_secret' => ['label' => 'PayPal: clau secreta', 'type' => 'password', 'secret' => true, 'default' => '', 'show_if' => 'payments_gateway:paypal'],

            'redsys_mode' => ['label' => 'Redsys: mode', 'type' => 'select', 'default' => 'test', 'show_if' => 'payments_gateway:redsys',
                'options' => ['test' => 'Proves (test)', 'live' => 'Producció (live)']],
            'redsys_merchant_code' => ['label' => 'Redsys: codi de comerç (FUC)', 'type' => 'text', 'default' => '', 'placeholder' => '999008881', 'show_if' => 'payments_gateway:redsys'],
            'redsys_terminal' => ['label' => 'Redsys: terminal', 'type' => 'text', 'default' => '1', 'show_if' => 'payments_gateway:redsys'],
            'redsys_key' => ['label' => 'Redsys: clau secreta del comerç', 'type' => 'password', 'secret' => true, 'default' => '', 'show_if' => 'payments_gateway:redsys',
                'help' => 'La cadena en base64 que dona el banc al portal d\'administració del TPV.'],
            'redsys_name' => ['label' => 'Redsys: nom del comerç', 'type' => 'text', 'default' => '', 'show_if' => 'payments_gateway:redsys',
                'help' => 'Màxim 25 caràcters. És el que veu qui paga a la pantalla del TPV.'],

            'payments_currency' => ['label' => 'Moneda', 'type' => 'select', 'default' => 'EUR', 'options' => ['EUR' => 'Euro (€)']],
            'payments_descriptor' => ['label' => 'Concepte a l\'extracte bancari', 'type' => 'text', 'default' => '', 'help' => 'Màxim 22 caràcters.'],
        ],
    ],

    'billing' => [
        'title' => 'Facturació',
        'icon' => 'file',
        'description' => 'Les dades amb què s\'emeten els rebuts i les factures de les vostres vendes. '
            . 'Són les vostres: qui compra un tiquet o s\'inscriu tracta amb vosaltres i amb ningú més.',
        'admin_only' => true,
        'fields' => [
            'billing_document' => ['label' => 'Què s\'emet de cada venda', 'type' => 'select', 'default' => 'receipt',
                'options' => ['receipt' => 'Un rebut', 'invoice' => 'Una factura'],
                'help' => 'Per poder emetre factura cal tenir totes les dades fiscals d\'aquí sota. Si en falta alguna, s\'emet un rebut.'],
            'billing_entity' => ['label' => 'Nom fiscal de l\'entitat', 'type' => 'text', 'default' => '',
                'help' => 'Si es deixa buit s\'utilitza l\'entitat responsable dels textos legals.'],
            'billing_nif' => ['label' => 'NIF', 'type' => 'text', 'default' => '', 'placeholder' => 'G12345678'],
            'billing_address' => ['label' => 'Adreça', 'type' => 'text', 'default' => '', 'placeholder' => 'Carrer Major, 1'],
            'billing_postcode' => ['label' => 'Codi postal', 'type' => 'text', 'default' => ''],
            'billing_town' => ['label' => 'Població', 'type' => 'text', 'default' => ''],
            'billing_province' => ['label' => 'Província', 'type' => 'text', 'default' => ''],
            'billing_country' => ['label' => 'País', 'type' => 'text', 'default' => 'Espanya'],
            'billing_email' => ['label' => 'Correu de facturació', 'type' => 'email', 'default' => ''],
            'billing_phone' => ['label' => 'Telèfon', 'type' => 'text', 'default' => ''],
            'billing_series_receipt' => ['label' => 'Sèrie dels rebuts', 'type' => 'text', 'default' => 'R', 'help' => 'Els números queden R-2026-0001, R-2026-0002…'],
            'billing_series_invoice' => ['label' => 'Sèrie de les factures', 'type' => 'text', 'default' => 'F'],
            'billing_tax_rate' => ['label' => 'IVA aplicat (%)', 'type' => 'text', 'default' => '0',
                'help' => 'Els preus que poseu s\'entenen amb l\'impost inclòs; al document se\'n desglossa la base. Moltes activitats esportives d\'entitats sense ànim de lucre hi estan exemptes: si és el vostre cas, deixeu-hi 0 i expliqueu-ho a la nota.'],
            'billing_tax_note' => ['label' => 'Nota quan no s\'hi aplica IVA', 'type' => 'text', 'default' => 'Operació exempta d\'IVA (art. 20.1.13è de la Llei 37/1992).'],
            'billing_notes' => ['label' => 'Nota al peu del document', 'type' => 'text', 'default' => ''],
        ],
    ],

    'email' => [
        'title' => 'Correu electrònic',
        'icon' => 'mail',
        'description' => 'Enviament dels correus de confirmació i avisos.',
        'admin_only' => true,
        'fields' => [
            'mail_transport' => ['label' => 'Mètode d\'enviament', 'type' => 'select', 'default' => 'mail', 'options' => ['mail' => 'Funció mail() del servidor', 'smtp' => 'Servidor SMTP', 'log' => 'Assaig: no enviar res'],
                'help' => 'Amb «assaig» els correus no surten del servidor, però queden al registre de correus com si s\'haguessin enviat. Serveix per provar-ho tot sense escriure a ningú.'],
            'mail_from_name' => ['label' => 'Nom del remitent', 'type' => 'text', 'default' => ''],
            'mail_from_email' => ['label' => 'Adreça del remitent', 'type' => 'email', 'default' => ''],
            'mail_reply_to' => ['label' => 'Respondre a', 'type' => 'email', 'default' => ''],
            'mail_admin_notify' => ['label' => 'Avisos a l\'organització', 'type' => 'email', 'default' => '', 'help' => 'Adreça que rep una còpia de cada comanda i inscripció.'],
            'mail_batch_size' => ['label' => 'Correus per tanda', 'type' => 'number', 'default' => '20', 'min' => '1', 'max' => '100',
                'help' => 'Als enviaments a les persones inscrites, quants correus s\'envien de cop. Si l\'allotjament en limita el nombre per hora, abaixeu-ho.'],
            'smtp_host' => ['label' => 'Servidor SMTP', 'type' => 'text', 'default' => ''],
            'smtp_port' => ['label' => 'Port SMTP', 'type' => 'number', 'default' => '587'],
            'smtp_secure' => ['label' => 'Xifratge', 'type' => 'select', 'default' => 'tls', 'options' => ['tls' => 'STARTTLS (587)', 'ssl' => 'SSL/TLS (465)', 'none' => 'Cap']],
            'smtp_user' => ['label' => 'Usuari SMTP', 'type' => 'text', 'default' => ''],
            'smtp_pass' => ['label' => 'Contrasenya SMTP', 'type' => 'password', 'secret' => true, 'default' => ''],
        ],
    ],

    'appearance' => [
        'title' => 'Aparença',
        'icon' => 'palette',
        'description' => 'Colors, logotip i elements visuals.',
        'fields' => [
            'brand_mark' => ['label' => 'Què surt al costat del nom', 'type' => 'select', 'default' => 'icon',
                'options' => ['icon' => 'Una icona d\'esport', 'logo' => 'El vostre logotip'],
                'help' => 'Si trieu el logotip i no n\'heu pujat cap, es fa servir la icona.'],
            'site_icon' => ['label' => 'Icona', 'type' => 'sport_icon', 'default' => 'run', 'show_if' => 'brand_mark:icon'],
            'logo' => ['label' => 'Logotip', 'type' => 'image', 'default' => '', 'show_if' => 'brand_mark:logo'],
            'favicon' => ['label' => 'Icona del navegador', 'type' => 'image', 'default' => ''],
            'color_primary' => ['label' => 'Color principal', 'type' => 'color', 'default' => '#2f6b3c'],
            'color_secondary' => ['label' => 'Color secundari', 'type' => 'color', 'default' => '#7ba05b'],
            'color_accent' => ['label' => 'Color d\'accent', 'type' => 'color', 'default' => '#c8552b'],
            'hero_overlay' => ['label' => 'Opacitat del vel del banner (%)', 'type' => 'number', 'default' => '55'],
            'vine_pattern' => ['label' => 'Mostrar il·lustració de vinyes', 'type' => 'bool', 'default' => '0',
                'help' => 'Una sanefa de vinyes al peu de la capçalera. Va bé a les curses del Penedès; a la resta, val més deixar-la apagada.'],
            'footer_text' => ['label' => 'Text del peu', 'type' => 'textarea', 'rows' => 3, 'default' => ''],
        ],
    ],

    'seo' => [
        'title' => 'SEO i cercadors',
        'icon' => 'globe',
        'description' => 'Com es veu el web a Google i quan algú el comparteix.',
        'fields' => [
            'meta_title' => ['label' => 'Títol per a cercadors', 'type' => 'text', 'default' => '',
                'help' => 'Opcional. El que surt a la pestanya del navegador i al resultat de Google per a la portada. Si ho deixeu buit es fa servir el nom del web i el lema. Va bé que tingui entre 50 i 60 lletres.'],
            'meta_description' => ['label' => 'Descripció per a cercadors', 'type' => 'textarea', 'rows' => 2, 'default' => '',
                'help' => 'Les dues línies que Google ensenya sota el títol. Entre 120 i 160 lletres va bé; si és més llarga, la talla.'],
            'og_image' => ['label' => 'Imatge destacada per a xarxes socials', 'type' => 'image', 'default' => '',
                'help' => 'La que surt quan algú comparteix el web per WhatsApp, Facebook o X. Millor apaisada i de 1200×630 píxels. Si no n\'hi ha cap, es fa servir la imatge del banner de la portada.'],
            'og_image_alt' => ['label' => 'Descripció de la imatge destacada', 'type' => 'text', 'default' => '',
                'help' => 'Una frase que digui què es veu a la imatge, per a qui no la pot veure.'],
            'meta_keywords' => ['label' => 'Paraules clau', 'type' => 'text', 'default' => '',
                'help' => 'Separades per comes: «cursa popular, cros escolar, el vostre poble». Google fa temps que no les té en compte per posicionar, però sí que s\'aprofiten a les dades estructurades i hi ha cercadors i xarxes que encara les llegeixen.'],
            'twitter_site' => ['label' => 'Compte d\'X (Twitter)', 'type' => 'text', 'default' => '',
                'help' => 'Amb l\'arrova: @elmeucompte. Surt a la targeta que es veu quan algú comparteix una pàgina del web.'],
            'seo_structured_data' => ['label' => 'Enviar dades estructurades als cercadors', 'type' => 'bool', 'default' => '1',
                'help' => 'Explica a Google què és la cursa, quan és i on, amb el format que entenen els cercadors (schema.org). Amb això la cursa pot sortir a la fitxa d\'esdeveniments.'],
            'seo_noindex' => ['label' => 'Demanar als cercadors que no indexin el web', 'type' => 'bool', 'default' => '0',
                'help' => 'Amaga el web de Google i companyia sense treure\'l de circulació. Útil si és una còpia de proves. Si el teniu marcat, el web no sortirà a cap cercador.'],
            'google_verification' => ['label' => 'Verificació de Google Search Console', 'type' => 'text', 'default' => '',
                'help' => 'A Search Console, trieu «Etiqueta HTML» i enganxeu aquí només el codi de dins de content="…". Serveix per demostrar que el web és vostre i veure com el troba la gent.'],
            'bing_verification' => ['label' => 'Verificació de Bing Webmaster Tools', 'type' => 'text', 'default' => '',
                'help' => 'Igual que l\'anterior, per al cercador de Microsoft (que és el que alimenta ChatGPT i Copilot).'],
        ],
    ],

    'legal' => [
        'title' => 'Textos legals',
        'icon' => 'file',
        'description' => 'Avís legal, privacitat i qui respon del web.',
        'fields' => [
            'legal_entity' => ['label' => 'Entitat responsable', 'type' => 'text', 'default' => '',
                'help' => 'Nom complet de l\'entitat que organitza la cursa i que respon de les dades. Surt als textos legals.'],
            'legal_notice' => ['label' => 'Avís legal', 'type' => 'html', 'rows' => 16, 'default' => '',
                'help' => 'Podeu escriure-hi {{entitat}}, {{cursa}}, {{poble}}, {{correu}}, {{telefon}} i {{web}}: en publicar-se, s\'hi posen les dades configurades. Si algun dia activeu el pagament en línia, reviseu el text: diu que no se\'n fa cap.'],
            'privacy_text' => ['label' => 'Política de privacitat', 'type' => 'html', 'rows' => 20, 'default' => '',
                'help' => 'Admet els mateixos marcadors que l\'avís legal. És un text de partida redactat segons el que recull aquest web: reviseu-lo i adapteu-lo a com treballeu, i si activeu el pagament en línia o afegiu serveis externs, actualitzeu-lo.'],
            'credits_label' => ['label' => 'Desenvolupat per', 'type' => 'text', 'default' => 'Octavi Rodríguez',
                'help' => 'Surt al peu de pàgina, al costat de l\'avís legal. Deixeu-ho buit per no mostrar-hi res.'],
            'credits_email' => ['label' => 'Correu de qui ha fet el web', 'type' => 'email', 'default' => 'octavi@soportic.es',
                'help' => 'Si n\'hi poseu un, el nom del peu hi enllaça.'],
        ],
    ],

    'updates' => [
        'title' => 'Actualitzacions',
        'icon' => 'refresh',
        'description' => 'Origen de les actualitzacions automàtiques (OTA).',
        'admin_only' => true,
        'fields' => [
            'update_manifest_url' => ['label' => 'URL del manifest', 'type' => 'url', 'default' => 'https://api.github.com/repos/soportic-orb/crosescolar/releases/latest', 'help' => 'Admet el format propi (manifest.json) i l\'API de versions de GitHub.'],
            'update_token' => ['label' => 'Token d\'accés', 'type' => 'password', 'secret' => true, 'default' => '', 'help' => 'Només cal per a dipòsits privats.'],
            'update_auto_check' => ['label' => 'Comprovar automàticament', 'type' => 'bool', 'default' => '1'],
            'update_backup' => ['label' => 'Fer còpia de seguretat abans d\'actualitzar', 'type' => 'bool', 'default' => '1'],
        ],
    ],
];
