<?php
/**
 * Esquema dels textos i opcions configurables des del panell d'administració.
 * Els formularis del panell es generen automàticament a partir d'aquest fitxer.
 *
 * Tipus disponibles: text, textarea, html, email, url, tel, number, money, date,
 * time, color, coord, bool, select, image, file, password.
 */
return [
    'general' => [
        'title' => 'Dades de la cursa',
        'icon' => 'calendar',
        'description' => 'Informació bàsica de l\'esdeveniment que es mostra a tot el web.',
        'fields' => [
            'site_name' => ['label' => 'Nom del web', 'type' => 'text', 'default' => 'Cros Escolar La Granada'],
            'site_tagline' => ['label' => 'Lema', 'type' => 'text', 'default' => 'Córrer entre vinyes a l\'Alt Penedès'],
            'event_date' => ['label' => 'Data de la cursa', 'type' => 'date', 'default' => '2026-10-04'],
            'event_time' => ['label' => 'Hora d\'inici', 'type' => 'time', 'default' => '09:30'],
            'event_place' => ['label' => 'Lloc de sortida', 'type' => 'text', 'default' => 'Zona esportiva de La Granada'],
            'event_address' => ['label' => 'Adreça', 'type' => 'text', 'default' => 'Carrer de Vilafranca, s/n — 08792 La Granada (Alt Penedès)'],
            'event_town' => ['label' => 'Població', 'type' => 'text', 'default' => 'La Granada, Alt Penedès'],
            'map_lat' => ['label' => 'Latitud de la sortida', 'type' => 'coord', 'axis' => 'lat', 'default' => '41.376699',
                'help' => 'Punt exacte que marca el mapa. A OpenStreetMap, feu clic dret al lloc i trieu «Mostra l\'adreça»; també hi podeu enganxar un enllaç del mapa i se\'n treuen les coordenades.'],
            'map_lng' => ['label' => 'Longitud de la sortida', 'type' => 'coord', 'axis' => 'lng', 'default' => '1.713535'],
            'map_embed' => ['label' => 'Enllaç del mapa', 'type' => 'text', 'default' => '',
                'help' => 'Opcional. Si enganxeu un enllaç d\'OpenStreetMap o de Google Maps, el punt es treu de l\'enllaç. Si deixeu buides les coordenades i l\'enllaç, el mapa cercarà l\'adreça escrita aquí sobre.'],
            'organizer' => ['label' => 'Organitza', 'type' => 'text', 'default' => 'AFA Escola La Granada'],
            'collaborators' => ['label' => 'Amb la col·laboració de', 'type' => 'text', 'default' => 'Ajuntament de La Granada i Consell Esportiu de l\'Alt Penedès'],
            'contact_email' => ['label' => 'Correu de contacte', 'type' => 'email', 'default' => 'cros@afalagranada.cat'],
            'contact_phone' => ['label' => 'Telèfon de contacte', 'type' => 'tel', 'default' => ''],
            'social_instagram' => ['label' => 'Instagram (URL)', 'type' => 'url', 'default' => ''],
            'social_facebook' => ['label' => 'Facebook (URL)', 'type' => 'url', 'default' => ''],
            'social_whatsapp' => ['label' => 'Grup de WhatsApp (URL)', 'type' => 'url', 'default' => ''],
            'pretty_urls' => ['label' => 'URLs amigables', 'type' => 'bool', 'default' => '1', 'help' => 'Desactiveu-ho només si el servidor no té la reescriptura d\'URL activada.'],
            'analytics_id' => ['label' => 'Identificador d\'analítica', 'type' => 'text', 'default' => '', 'help' => 'Opcional. Codi de Google Analytics 4 (G-XXXXXXX) o Matomo.'],
        ],
    ],

    'coming_soon' => [
        'title' => 'Web en preparació',
        'icon' => 'eye',
        'description' => 'Amaga el web al públic i mostra només un avís. Les persones amb sessió iniciada al panell continuen veient el web complet.',
        'fields' => [
            'coming_soon' => ['label' => 'Amagar el web al públic', 'type' => 'bool', 'default' => '0',
                'help' => 'Mentre estigui activat, qualsevol visitant veurà l\'avís «Aviat publicarem el web».'],
            'coming_soon_title' => ['label' => 'Títol de l\'avís', 'type' => 'text', 'default' => 'Aviat publicarem el web'],
            'coming_soon_text' => ['label' => 'Text de l\'avís', 'type' => 'html', 'rows' => 5,
                'default' => '<p>Estem preparant el web del Cros Escolar La Granada amb tota la informació de la cursa, els recorreguts i els tiquets del punt de recàrrega.</p><p>Torneu-hi ben aviat!</p>'],
            'coming_soon_image' => ['label' => 'Imatge de fons', 'type' => 'image', 'default' => '',
                'help' => 'Opcional. Si no n\'hi ha cap, es fa servir la del banner de la portada o el fons il·lustrat de vinyes.'],
            'coming_soon_countdown' => ['label' => 'Mostrar la data i el compte enrere', 'type' => 'bool', 'default' => '1'],
            'coming_soon_contact' => ['label' => 'Mostrar el contacte i les xarxes', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'home' => [
        'title' => 'Portada',
        'icon' => 'home',
        'description' => 'Banner principal i textos de la pàgina d\'inici.',
        'fields' => [
            'hero_image' => ['label' => 'Imatge del banner', 'type' => 'image', 'default' => '', 'help' => 'Recomanat 1920×1080 px. Si no n\'hi ha cap, es mostra el fons il·lustrat de vinyes.'],
            'hero_badge' => ['label' => 'Etiqueta superior', 'type' => 'text', 'default' => 'X Cros Escolar'],
            'hero_title' => ['label' => 'Títol del banner', 'type' => 'text', 'default' => 'Cros Escolar La Granada'],
            'hero_subtitle' => ['label' => 'Subtítol del banner', 'type' => 'textarea', 'rows' => 2, 'default' => 'Una matinal d\'esport i festa entre les vinyes del Penedès per a totes les edats.'],
            'hero_cta_label' => ['label' => 'Botó principal (text)', 'type' => 'text', 'default' => 'Inscripcions al cros'],
            'hero_cta_url' => ['label' => 'Botó principal (enllaç)', 'type' => 'text', 'default' => '/inscripcio'],
            'hero_cta2_label' => ['label' => 'Botó secundari (text)', 'type' => 'text', 'default' => 'Categories i premis'],
            'hero_cta2_url' => ['label' => 'Botó secundari (enllaç)', 'type' => 'text', 'default' => '/categories-i-premis'],
            'countdown_enabled' => ['label' => 'Mostrar compte enrere', 'type' => 'bool', 'default' => '1'],
            'intro_title' => ['label' => 'Títol de la introducció', 'type' => 'text', 'default' => 'La cursa del poble'],
            'intro_text' => ['label' => 'Text de la introducció', 'type' => 'html', 'rows' => 6, 'default' => '<p>El Cros Escolar de La Granada és una matinal esportiva oberta a infants, joves i famílies. Un recorregut entre vinyes, camins i carrers del poble per gaudir de l\'esport en equip, tant si competeixes com si només vens a passar-ho bé.</p><p>En acabar les curses hi haurà lliurament de premis i punt de recàrrega a la zona esportiva, per recuperar forces.</p>'],
            'courses_title' => ['label' => 'Títol dels recorreguts', 'type' => 'text', 'default' => 'Els recorreguts'],
            'courses_intro' => ['label' => 'Text dels recorreguts', 'type' => 'textarea', 'rows' => 3, 'default' => 'Tots els circuits estan senyalitzats i controlats per voluntariat. Pots consultar-los al mapa de Wikiloc i descarregar el track per al teu rellotge.'],
            'schedule_title' => ['label' => 'Títol del programa', 'type' => 'text', 'default' => 'Programa de la jornada'],
            'schedule_intro' => ['label' => 'Text del programa', 'type' => 'textarea', 'rows' => 2, 'default' => 'Els horaris són orientatius i poden variar lleugerament segons la participació.'],
            'gallery_title' => ['label' => 'Títol de la galeria', 'type' => 'text', 'default' => 'Edicions anteriors'],
            'location_title' => ['label' => 'Títol de la ubicació', 'type' => 'text', 'default' => 'Com arribar-hi'],
            'location_text' => ['label' => 'Text de la ubicació', 'type' => 'textarea', 'rows' => 3, 'default' => 'La Granada és a 5 minuts de Vilafranca del Penedès. Hi ha aparcament gratuït a la zona esportiva i estació de Rodalies (R4) a 10 minuts a peu.'],
            'sponsors_title' => ['label' => 'Títol dels patrocinadors', 'type' => 'text', 'default' => 'Amb el suport de'],
            'sponsors_intro' => ['label' => 'Text dels patrocinadors', 'type' => 'textarea', 'rows' => 2, 'default' => 'Gràcies a les entitats i empreses que fan possible el cros escolar.'],
        ],
    ],

    'tickets' => [
        'title' => 'Punt de recàrrega i tiquets',
        'icon' => 'ticket',
        'description' => 'El punt de recàrrega és el servei de bar de la cursa: on es recuperen forces en acabar. Aquí se\'n configuren la informació i els tiquets.',
        'fields' => [
            'tickets_public_mode' => ['label' => 'Què es mostra al web', 'type' => 'select', 'default' => 'info', 'options' => [
                'info' => 'Només informació (sense compra en línia)',
                'sale' => 'Informació i venda en línia amb targeta',
            ], 'help' => 'Amb «només informació» el web explica el punt de recàrrega i els preus, però no s\'hi pot comprar. La gestió de tiquets, comandes i validació continua al panell.'],
            'tickets_enabled' => ['label' => 'Venda en línia oberta', 'type' => 'bool', 'default' => '1',
                'help' => 'Només té efecte si heu triat la venda en línia.'],
            'tickets_title' => ['label' => 'Títol de la pàgina', 'type' => 'text', 'default' => 'Tiquets del punt de recàrrega'],
            'tickets_intro' => ['label' => 'Introducció', 'type' => 'html', 'rows' => 5, 'default' => '<p>En acabar les curses obrirem el punt de recàrrega a la zona esportiva: entrepans, beguda i fruita per recuperar l\'energia gastada corrent. Els tiquets es podran comprar a la carpa de l\'AFA el mateix dia de la cursa.</p>'],
            'tickets_deadline' => ['label' => 'Data límit de venda', 'type' => 'date', 'default' => '2026-10-02', 'help' => 'Després d\'aquesta data la botiga es tanca automàticament.'],
            'tickets_max_per_order' => ['label' => 'Màxim d\'unitats per comanda', 'type' => 'number', 'default' => '20'],
            'tickets_info' => ['label' => 'Informació pràctica', 'type' => 'html', 'rows' => 4, 'default' => '<ul><li>Els tiquets es venen el mateix dia a la carpa de l\'AFA.</li><li>Es poden pagar en efectiu o amb targeta.</li><li>Hi haurà opcions vegetarianes i sense gluten.</li></ul>'],
            'tickets_terms' => ['label' => 'Condicions de compra', 'type' => 'html', 'rows' => 4, 'default' => '<p>La compra de tiquets és una col·laboració amb l\'AFA de l\'Escola La Granada. En cas de suspensió de l\'esdeveniment es retornarà l\'import íntegre.</p>'],
            'tickets_closed_text' => ['label' => 'Text quan la venda està tancada', 'type' => 'html', 'rows' => 3, 'default' => '<p>La venda anticipada de tiquets ja està tancada. El mateix dia de la cursa en podreu comprar a la carpa de l\'AFA fins a exhaurir existències.</p>'],
            'tickets_success_text' => ['label' => 'Text de confirmació de compra', 'type' => 'html', 'rows' => 3, 'default' => '<p>Gràcies per col·laborar amb l\'AFA! Rebràs els tiquets per correu electrònic. També els pots consultar sempre que vulguis des d\'aquesta pàgina.</p>'],
            'tickets_email_intro' => ['label' => 'Text del correu de confirmació', 'type' => 'textarea', 'rows' => 3, 'default' => 'Gràcies per comprar els tiquets del punt de recàrrega del Cros Escolar La Granada. Presenta aquest correu o el codi QR de cada tiquet a la carpa de l\'AFA.'],
        ],
    ],

    'categories' => [
        'title' => 'Categories i premis',
        'icon' => 'trophy',
        'description' => 'Textos de la pàgina de categories, horaris i premis.',
        'fields' => [
            'categories_title' => ['label' => 'Títol de la pàgina', 'type' => 'text', 'default' => 'Categories i premis'],
            'categories_intro' => ['label' => 'Introducció', 'type' => 'html', 'rows' => 4, 'default' => '<p>Hi ha una cursa per a cada edat, des de P3 fins a les curses d\'adults i famílies. Consulta la teva categoria, l\'hora de sortida i la distància del recorregut.</p>'],
            'categories_notes' => ['label' => 'Notes finals', 'type' => 'html', 'rows' => 4, 'default' => '<p>Totes les persones participants rebran un obsequi de record. Cal ser al lloc de sortida 10 minuts abans de l\'hora indicada.</p>'],
            'prizes_title' => ['label' => 'Títol dels premis', 'type' => 'text', 'default' => 'Premis'],
            'prizes_intro' => ['label' => 'Introducció dels premis', 'type' => 'textarea', 'rows' => 3, 'default' => 'El lliurament de premis es farà a l\'escenari de la zona esportiva en acabar l\'última cursa.'],
            'prizes_local_label' => ['label' => 'Nom del premi local', 'type' => 'text', 'default' => 'Primer local',
                'help' => 'Premi per al primer classificat de l\'escola del poble dins de cada categoria. A cada categoria podeu decidir si el doneu, i el guanyador es marca a mà a Resultats.'],
            'prizes_local_school' => ['label' => 'Escola del poble', 'type' => 'text', 'default' => 'Escola La Granada',
                'help' => 'Serveix per assenyalar-vos al panell qui hi pot optar. El premi el marqueu vosaltres: el nom de l\'escola es pot haver escrit de mil maneres.'],
        ],
    ],

    'rules' => [
        'title' => 'Reglament',
        'icon' => 'file',
        'description' => 'Reglament de la cursa. Es publica en una pàgina pròpia i s\'ha d\'acceptar en inscriure\'s.',
        'fields' => [
            'rules_title' => ['label' => 'Títol de la pàgina', 'type' => 'text', 'default' => 'Reglament de la cursa'],
            'rules_text' => ['label' => 'Text del reglament', 'type' => 'html', 'rows' => 22, 'default' => '<h2>1. La cursa</h2><p>El {{cursa}} és una cursa popular de caràcter no competitiu, oberta a totes les edats, organitzada per l\'{{entitat}} a {{poble}}. Es fa el dia i a l\'hora anunciats al web, amb sortida i arribada a la zona esportiva.</p><h2>2. Qui hi pot participar</h2><p>Hi pot participar qualsevol persona, sigui o no de l\'escola i del poble. Cada participant corre a la categoria que li correspon per any de naixement; l\'organització l\'assigna automàticament en fer la inscripció. Les persones menors d\'edat han de ser inscrites pel pare, la mare o qui en tingui la tutela legal.</p><h2>3. Inscripcions</h2><p>La inscripció és gratuïta i es fa pel web fins a la data de tancament que s\'hi indica. Cal emplenar un formulari per cada participant. Les dades s\'han de facilitar correctament: l\'any de naixement determina la categoria i una dada errònia pot deixar el resultat sense validesa.</p><p>Un cop tancades les inscripcions en línia, qui vulgui apuntar-s\'hi encara ho pot fer a la carpa de l\'organització el mateix dia, fins a 30 minuts abans de la sortida de la seva categoria, mentre hi hagi dorsals disponibles.</p><h2>4. Dorsals</h2><p>Cada participant rep un número de dorsal en inscriure\'s. El dorsal es recull el mateix dia a la zona esportiva i s\'ha de portar col·locat al pit, sencer i ben visible, durant tota la cursa. El dorsal és personal i intransferible: no es pot córrer amb el dorsal d\'una altra persona.</p><h2>5. Horaris i sortides</h2><p>Els horaris de cada categoria es publiquen al web i poden variar lleugerament segons la participació. Cal ser a la zona de sortida <strong>15 minuts abans</strong> de l\'hora prevista. Qui no hi sigui a l\'hora de la sortida pot sortir igualment, però ho farà darrere del grup.</p><h2>6. Recorregut</h2><p>Els recorreguts estan senyalitzats i controlats per persones voluntàries, a les quals cal fer cas en tot moment. S\'ha de seguir el recorregut marcat de principi a fi: escurçar-lo o sortir-ne comporta quedar fora de la classificació. Hi pot haver trams de camí, terra o carrer obert al trànsit controlat.</p><h2>7. Classificacions i premis</h2><p>L\'ordre d\'arribada de cada categoria es pren a meta. Els resultats es publiquen al web un cop acabada la jornada. Els premis de cada categoria i el premi al primer classificat de l\'escola del poble es detallen a la pàgina de categories i premis, i es lliuren a la zona esportiva en acabar l\'última cursa. Cal ser-hi present per recollir-los.</p><h2>8. Acompanyants</h2><p>A les categories més petites s\'hi admet una persona acompanyant per infant, que ha de córrer per fora del grup i sense destorbar la resta. Les persones acompanyants no consten a la classificació. No es pot participar amb bicicleta, patins ni animals de companyia.</p><h2>9. Salut i seguretat</h2><p>Cada participant, o qui en tingui la tutela legal, declara que està en condicions físiques adequades per fer la cursa i hi participa sota la seva responsabilitat. Qui pateixi alguna afecció que calgui tenir en compte ho pot fer constar a les observacions del formulari d\'inscripció. Durant la jornada hi ha servei d\'assistència sanitària bàsica.</p><p>L\'organització pot retirar de la cursa qualsevol participant que, a criteri del personal sanitari o de l\'organització, no estigui en condicions de continuar.</p><h2>10. Canvis i suspensió</h2><p>L\'organització pot modificar els horaris, els recorreguts o qualsevol altre aspecte de la jornada, i també ajornar-la o suspendre-la, per motius de seguretat, meteorològics o de força major. Els canvis es comuniquen pel web i, si cal, per correu electrònic a les persones inscrites.</p><h2>11. Dades personals i imatges</h2><p>Les dades de la inscripció es tracten tal com s\'explica a la <a href="/privacitat">política de privacitat</a>. Durant la cursa es fan fotografies i vídeos de l\'activitat, que es poden publicar als canals de l\'AFA i de l\'escola només si s\'ha autoritzat expressament al formulari d\'inscripció.</p><h2>12. Acceptació</h2><p>Inscriure\'s a la cursa implica acceptar aquest reglament i les indicacions de l\'organització i del voluntariat. Qualsevol cas no previst aquí el resol l\'organització.</p>',
                'help' => 'Es publica a /reglament i s\'enllaça des del formulari d\'inscripció i del peu de pàgina. Admet els mateixos marcadors que els textos legals: {{entitat}}, {{cursa}}, {{poble}}, {{correu}}, {{telefon}} i {{web}}.'],
            'rules_consent' => ['label' => 'Demanar que s\'accepti en inscriure\'s', 'type' => 'bool', 'default' => '1',
                'help' => 'Afegeix una casella al formulari d\'inscripció. Si la desactiveu, la pàgina del reglament continua publicada però no es demana acceptar-lo.'],
            'rules_consent_label' => ['label' => 'Text de la casella', 'type' => 'text', 'default' => 'Accepto el reglament de la cursa',
                'show_if' => 'rules_consent',
                'help' => 'Al formulari, aquest text fa d\'enllaç al reglament.'],
        ],
    ],

    'registrations' => [
        'title' => 'Inscripcions',
        'icon' => 'users',
        'description' => 'Inscripció a les curses. Podeu tenir el formulari en línia actiu o mostrar només un text informatiu.',
        'fields' => [
            'registrations_enabled' => ['label' => 'Formulari d\'inscripció en línia actiu', 'type' => 'bool', 'default' => '1',
                'help' => 'Si el desactiveu, la pàgina d\'inscripció només mostrarà el text informatiu de més avall, sense cap formulari.'],
            'registrations_title' => ['label' => 'Títol de la pàgina', 'type' => 'text', 'default' => 'Inscripció a la cursa'],
            'registrations_intro' => ['label' => 'Introducció (només amb el formulari actiu)', 'type' => 'html', 'rows' => 4, 'default' => '<p>La inscripció és gratuïta per a l\'alumnat de l\'escola i per a totes les persones que vulguin participar. Empleneu un formulari per cada participant.</p>'],
            'registrations_aside' => ['label' => 'Mostrar el requadre de recordatoris', 'type' => 'bool', 'default' => '1',
                'help' => 'És el requadre que surt al costat del formulari, amb el que cal tenir present abans d\'inscriure\'s.'],
            'registrations_aside_title' => ['label' => 'Títol del requadre', 'type' => 'text', 'default' => 'Recorda', 'show_if' => 'registrations_aside'],
            'registrations_aside_text' => ['label' => 'Contingut del requadre', 'type' => 'html', 'rows' => 6, 'show_if' => 'registrations_aside',
                'default' => '<ul><li>Cal omplir un formulari per cada participant.</li><li>Els dorsals es recullen el mateix dia a la zona esportiva.</li><li>Arribeu 15 minuts abans de la vostra sortida.</li><li>El punt de recàrrega té tiquet a part: <a href="/punt-de-recarrega">mira-ho aquí</a>.</li></ul>'],
            'registrations_close_at' => ['label' => 'Data de tancament del formulari', 'type' => 'date', 'default' => '2026-10-02',
                'help' => 'Passada aquesta data el formulari es tanca sol i es mostra el text informatiu. Deixeu-ho buit per no posar-hi data límit.'],
            'registrations_closed_text' => ['label' => 'Text informatiu (sense formulari)', 'type' => 'html', 'rows' => 5, 'default' => '<p>Enguany les inscripcions no es fan per internet. El mateix dia de la cursa hi haurà inscripcions presencials a la carpa de l\'AFA fins a 30 minuts abans de cada sortida.</p>', 'help' => 'És l\'únic que es veurà a la pàgina quan el formulari estigui desactivat o s\'hagi passat la data.'],
            'registrations_closed_link_label' => ['label' => 'Botó opcional: text', 'type' => 'text', 'default' => '', 'placeholder' => 'Descarregar el full d\'inscripció'],
            'registrations_closed_link_url' => ['label' => 'Botó opcional: enllaç', 'type' => 'text', 'default' => '', 'placeholder' => 'https://…  o  /punt-de-recarrega',
                'help' => 'Si ompliu els dos camps, sota el text hi apareixerà un botó (per exemple cap a un PDF o a un formulari extern).'],
            'registrations_success_text' => ['label' => 'Text de confirmació', 'type' => 'html', 'rows' => 3, 'default' => '<p>Inscripció rebuda! Us hem enviat un correu de confirmació amb les dades. Ens veiem el dia de la cursa.</p>'],
            'registrations_selfservice' => ['label' => '«Les meves inscripcions» actiu', 'type' => 'bool', 'default' => '1',
                'help' => 'Permet que les famílies entrin amb un codi que reben per correu per revisar i modificar les dades dels seus participants. Si ho desactiveu, la pàgina deixa d\'existir.'],
            'registrations_notify' => ['label' => 'Avisar per correu de cada inscripció', 'type' => 'bool', 'default' => '1'],
            'registrations_consent' => ['label' => 'Text del consentiment de dades', 'type' => 'textarea', 'rows' => 3, 'default' => 'Accepto que les dades facilitades s\'utilitzin únicament per gestionar la participació al Cros Escolar La Granada.'],
            'registrations_image_consent' => ['label' => 'Text del consentiment d\'imatge', 'type' => 'textarea', 'rows' => 3, 'default' => 'Autoritzo la publicació d\'imatges de l\'esdeveniment als canals de l\'AFA i de l\'escola.'],
        ],
    ],

    'bibs' => [
        'title' => 'Dorsals',
        'icon' => 'flag',
        'description' => 'Maqueta dels dorsals i on s\'hi col·loquen les dades de cada participant. Les posicions es mesuren en mil·límetres des de la cantonada superior esquerra.',
        'fields' => [
            'bib_public_download' => ['label' => 'Les famílies poden descarregar el dorsal', 'type' => 'bool', 'default' => '1',
                'help' => 'Si ho desactiveu, l\'enllaç per descarregar el dorsal desapareix del web, de «Les meves inscripcions» i dels correus de confirmació. Des del panell els podreu continuar imprimint.'],
            'bib_template' => ['label' => 'Maqueta del dorsal (PDF)', 'type' => 'file', 'folder' => 'documents', 'accept' => '.pdf', 'default' => '', 'help' => 'Pugeu el disseny en PDF. Si no n\'hi ha cap, els dorsals es generen sobre un fons blanc.'],
            'bib_template_page' => ['label' => 'Pàgina de la maqueta', 'type' => 'number', 'default' => '1', 'help' => 'Per si el PDF té més d\'una pàgina.'],
            'bib_orientation' => ['label' => 'Orientació del dorsal', 'type' => 'select', 'default' => 'auto',
                'options' => ['auto' => 'La mateixa que la maqueta', 'portrait' => 'Vertical', 'landscape' => 'Horitzontal'],
                'help' => 'Amb «la mateixa que la maqueta» el dorsal surt amb la mida i l\'orientació del PDF que heu pujat. Si en marqueu una altra, la maqueta es gira per omplir la pàgina: és el cas d\'un disseny apaïsat desat en un PDF vertical. Després de canviar-la, reviseu les posicions de més avall amb el botó «Dorsal de prova».'],
            'bib_template_rotate' => ['label' => 'Gir de la maqueta', 'type' => 'select', 'default' => '0',
                'options' => ['0' => 'Cap', '90' => '90° cap a l\'esquerra', '180' => 'Del revés (180°)', '270' => '90° cap a la dreta'],
                'help' => 'Només si la maqueta surt de costat o del revés: el gir s\'aplica abans de l\'orientació. Comproveu-ho amb el botó «Dorsal de prova».'],
            'bib_page_size' => ['label' => 'Mida quan no hi ha maqueta', 'type' => 'select', 'default' => 'a5', 'options' => ['a4' => 'A4 (210×297 mm)', 'a5' => 'A5 (148×210 mm)', 'a6' => 'A6 (105×148 mm)'],
                'help' => 'L\'orientació de més amunt també s\'hi aplica.'],
            'bib_two_per_sheet' => ['label' => 'Dos dorsals per full A4', 'type' => 'bool', 'default' => '0',
                'help' => 'En imprimir-los, cada full A4 vertical porta dos dorsals, un a dalt i un a baix, per gastar la meitat de paper. Només s\'aplica si el dorsal hi cap: un A5 apaïsat (210×148 mm) o més petit. Si és més gran, se\'n continua fent un per full.'],
            'bib_digits' => ['label' => 'Xifres del número de dorsal', 'type' => 'number', 'default' => '3', 'help' => 'Amb 3 xifres, el dorsal 1 es mostra com a 001.'],
            'bib_number_show' => ['label' => 'Mostrar el número', 'type' => 'bool', 'default' => '1'],
            'bib_number_x' => ['label' => 'El número: posició X (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '74'],
            'bib_number_y' => ['label' => 'El número: posició Y (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '120'],
            'bib_number_size' => ['label' => 'El número: mida de lletra (pt)', 'type' => 'number', 'step' => '0.5', 'default' => '90'],
            'bib_number_color' => ['label' => 'El número: color', 'type' => 'color', 'default' => '#12301c'],
            'bib_number_align' => ['label' => 'El número: alineació', 'type' => 'select', 'default' => 'center', 'options' => ['left' => 'Esquerra', 'center' => 'Centrat', 'right' => 'Dreta']],
            'bib_number_bold' => ['label' => 'El número: negreta', 'type' => 'bool', 'default' => '1'],
            'bib_name_show' => ['label' => 'Mostrar el nom', 'type' => 'bool', 'default' => '1'],
            'bib_name_first_only' => ['label' => 'Només el nom, sense cognoms', 'type' => 'bool', 'default' => '0',
                'show_if' => 'bib_name_show',
                'help' => 'Al dorsal hi surt «Laia» en lloc de «Laia Ferrer Miró». Va bé quan el dorsal és petit o quan es vol que s\'hi llegeixi de lluny.'],
            'bib_name_x' => ['label' => 'El nom: posició X (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '74'],
            'bib_name_y' => ['label' => 'El nom: posició Y (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '150'],
            'bib_name_size' => ['label' => 'El nom: mida de lletra (pt)', 'type' => 'number', 'step' => '0.5', 'default' => '18'],
            'bib_name_color' => ['label' => 'El nom: color', 'type' => 'color', 'default' => '#12301c'],
            'bib_name_align' => ['label' => 'El nom: alineació', 'type' => 'select', 'default' => 'center', 'options' => ['left' => 'Esquerra', 'center' => 'Centrat', 'right' => 'Dreta']],
            'bib_name_bold' => ['label' => 'El nom: negreta', 'type' => 'bool', 'default' => '0'],
            'bib_category_show' => ['label' => 'Mostrar la categoria', 'type' => 'bool', 'default' => '1'],
            'bib_category_x' => ['label' => 'La categoria: posició X (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '74'],
            'bib_category_y' => ['label' => 'La categoria: posició Y (mm)', 'type' => 'number', 'step' => '0.5', 'default' => '163'],
            'bib_category_size' => ['label' => 'La categoria: mida de lletra (pt)', 'type' => 'number', 'step' => '0.5', 'default' => '12'],
            'bib_category_color' => ['label' => 'La categoria: color', 'type' => 'color', 'default' => '#4a5b50'],
            'bib_category_align' => ['label' => 'La categoria: alineació', 'type' => 'select', 'default' => 'center', 'options' => ['left' => 'Esquerra', 'center' => 'Centrat', 'right' => 'Dreta']],
            'bib_category_bold' => ['label' => 'La categoria: negreta', 'type' => 'bool', 'default' => '0'],
        ],
    ],

    'results' => [
        'title' => 'Resultats',
        'icon' => 'trophy',
        'description' => 'Publicació dels resultats de la cursa al web.',
        'fields' => [
            'results_published' => ['label' => 'Publicar els resultats al web', 'type' => 'bool', 'default' => '0', 'help' => 'Mentre no estigui activat, els resultats només es veuen des del panell.'],
            'results_title' => ['label' => 'Títol de la pàgina', 'type' => 'text', 'default' => 'Resultats de la cursa'],
            'results_intro' => ['label' => 'Introducció', 'type' => 'html', 'rows' => 4, 'default' => '<p>Classificació per categories del Cros Escolar La Granada. Enhorabona a totes les persones participants!</p>'],
            'results_note' => ['label' => 'Nota final', 'type' => 'html', 'rows' => 3, 'default' => '<p>Si detecteu cap errada a la classificació, escriviu-nos i la corregirem.</p>'],
            'results_show_bib' => ['label' => 'Mostrar el número de dorsal', 'type' => 'bool', 'default' => '1'],
            'results_public_pdf' => ['label' => 'Permetre descarregar els resultats en PDF', 'type' => 'bool', 'default' => '1'],
        ],
    ],

    'payments' => [
        'title' => 'Pagaments (Stripe)',
        'icon' => 'card',
        'description' => 'Credencials de Stripe per cobrar els tiquets. Les claus es desen xifrades.',
        'admin_only' => true,
        'fields' => [
            'stripe_mode' => ['label' => 'Mode', 'type' => 'select', 'default' => 'test', 'options' => ['test' => 'Proves (test)', 'live' => 'Producció (live)']],
            'stripe_pk_test' => ['label' => 'Clau pública de proves', 'type' => 'text', 'default' => '', 'placeholder' => 'pk_test_...'],
            'stripe_sk_test' => ['label' => 'Clau secreta de proves', 'type' => 'password', 'secret' => true, 'default' => '', 'placeholder' => 'sk_test_...'],
            'stripe_webhook_test' => ['label' => 'Secret del webhook (proves)', 'type' => 'password', 'secret' => true, 'default' => '', 'placeholder' => 'whsec_...'],
            'stripe_pk_live' => ['label' => 'Clau pública de producció', 'type' => 'text', 'default' => '', 'placeholder' => 'pk_live_...'],
            'stripe_sk_live' => ['label' => 'Clau secreta de producció', 'type' => 'password', 'secret' => true, 'default' => '', 'placeholder' => 'sk_live_...'],
            'stripe_webhook_live' => ['label' => 'Secret del webhook (producció)', 'type' => 'password', 'secret' => true, 'default' => '', 'placeholder' => 'whsec_...'],
            'payments_currency' => ['label' => 'Moneda', 'type' => 'select', 'default' => 'EUR', 'options' => ['EUR' => 'Euro (€)']],
            'payments_descriptor' => ['label' => 'Concepte a l\'extracte bancari', 'type' => 'text', 'default' => 'CROS LA GRANADA', 'help' => 'Màxim 22 caràcters.'],
        ],
    ],

    'email' => [
        'title' => 'Correu electrònic',
        'icon' => 'mail',
        'description' => 'Enviament dels correus de confirmació i avisos.',
        'admin_only' => true,
        'fields' => [
            'mail_transport' => ['label' => 'Mètode d\'enviament', 'type' => 'select', 'default' => 'mail', 'options' => ['mail' => 'Funció mail() del servidor', 'smtp' => 'Servidor SMTP', 'log' => 'Assaig: no enviar res'],
                'help' => 'Amb «assaig» els correus no surten del servidor, però queden al registre de correus com si s\'haguessin enviat. Serveix per provar-ho tot sense escriure a ningú.'],
            'mail_from_name' => ['label' => 'Nom del remitent', 'type' => 'text', 'default' => 'Cros Escolar La Granada'],
            'mail_from_email' => ['label' => 'Adreça del remitent', 'type' => 'email', 'default' => ''],
            'mail_reply_to' => ['label' => 'Respondre a', 'type' => 'email', 'default' => ''],
            'mail_admin_notify' => ['label' => 'Avisos a l\'organització', 'type' => 'email', 'default' => '', 'help' => 'Adreça que rep una còpia de cada comanda i inscripció.'],
            'mail_batch_size' => ['label' => 'Correus per tanda', 'type' => 'number', 'default' => '20', 'min' => '1', 'max' => '100',
                'help' => 'Als enviaments a les persones inscrites, quants correus s\'envien de cop. Si l\'allotjament en limita el nombre per hora, abaixeu-ho.'],
            'smtp_host' => ['label' => 'Servidor SMTP', 'type' => 'text', 'default' => ''],
            'smtp_port' => ['label' => 'Port SMTP', 'type' => 'number', 'default' => '587'],
            'smtp_secure' => ['label' => 'Xifratge', 'type' => 'select', 'default' => 'tls', 'options' => ['tls' => 'STARTTLS (587)', 'ssl' => 'SSL/TLS (465)', 'none' => 'Cap']],
            'smtp_user' => ['label' => 'Usuari SMTP', 'type' => 'text', 'default' => ''],
            'smtp_pass' => ['label' => 'Contrasenya SMTP', 'type' => 'password', 'secret' => true, 'default' => ''],
        ],
    ],

    'appearance' => [
        'title' => 'Aparença',
        'icon' => 'palette',
        'description' => 'Colors, logotip i elements visuals.',
        'fields' => [
            'logo' => ['label' => 'Logotip', 'type' => 'image', 'default' => ''],
            'favicon' => ['label' => 'Icona del navegador', 'type' => 'image', 'default' => ''],
            'color_primary' => ['label' => 'Color principal', 'type' => 'color', 'default' => '#2f6b3c'],
            'color_secondary' => ['label' => 'Color secundari', 'type' => 'color', 'default' => '#7ba05b'],
            'color_accent' => ['label' => 'Color d\'accent', 'type' => 'color', 'default' => '#c8552b'],
            'hero_overlay' => ['label' => 'Opacitat del vel del banner (%)', 'type' => 'number', 'default' => '55'],
            'vine_pattern' => ['label' => 'Mostrar il·lustració de vinyes', 'type' => 'bool', 'default' => '1'],
            'footer_text' => ['label' => 'Text del peu', 'type' => 'textarea', 'rows' => 3, 'default' => 'Cros Escolar La Granada — organitzat per l\'AFA de l\'Escola La Granada amb la col·laboració de l\'Ajuntament de La Granada.'],
        ],
    ],

    'seo' => [
        'title' => 'SEO i legal',
        'icon' => 'globe',
        'description' => 'Metadades per a cercadors i textos legals.',
        'fields' => [
            'meta_description' => ['label' => 'Descripció per a cercadors', 'type' => 'textarea', 'rows' => 2, 'default' => 'Cros Escolar La Granada: cursa popular entre vinyes de l\'Alt Penedès per a totes les edats. Inscripcions, recorreguts i tiquets del punt de recàrrega.'],
            'og_image' => ['label' => 'Imatge per a xarxes socials', 'type' => 'image', 'default' => ''],
            'legal_entity' => ['label' => 'Entitat responsable', 'type' => 'text', 'default' => 'AFA Jacint Verdaguer de La Granada',
                'help' => 'Nom complet de l\'entitat que organitza la cursa i que respon de les dades. Surt als textos legals.'],
            'legal_notice' => ['label' => 'Avís legal', 'type' => 'html', 'rows' => 16, 'default' => '<h2>Qui som</h2><p>Aquest lloc web és titularitat de l\'<strong>{{entitat}}</strong>, associació sense ànim de lucre de mares i pares d\'alumnes de l\'Escola Jacint Verdaguer de La Granada (Alt Penedès), que organitza el {{cursa}}. Podeu contactar amb nosaltres a {{correu}}.</p><h2>Per a què serveix aquest web</h2><p>El web informa de la cursa (recorreguts, categories, horaris i premis), permet inscriure-s\'hi, consultar i modificar les pròpies inscripcions i consultar els resultats un cop publicats. La informació s\'ofereix de manera gratuïta i sense cap obligació de registre per navegar-hi.</p><p><strong>Aquest web no fa cap cobrament en línia.</strong> Els tiquets del punt de recàrrega, si n\'hi ha, es paguen presencialment el dia de la cursa. No us demanarem mai dades bancàries ni de targeta, ni pel web ni per correu electrònic.</p><h2>Condicions d\'ús</h2><p>En fer servir el web us comprometeu a fer-ne un ús correcte i a no utilitzar-lo per a finalitats il·lícites o que perjudiquin tercers. Les dades que faciliteu als formularis han de ser certes; qui inscriu una persona menor d\'edat ha de ser el pare, la mare o qui en tingui la tutela legal.</p><p>La inscripció a la cursa implica acceptar-ne el reglament i les indicacions de l\'organització i del voluntariat. Participar-hi és responsabilitat de cada persona participant o de qui en tingui la tutela: cal estar en condicions físiques adequades per fer-ho.</p><h2>Canvis i suspensió de la cursa</h2><p>L\'organització pot modificar els horaris, els recorreguts o qualsevol altre aspecte de la jornada, i també suspendre-la, per motius de seguretat, meteorològics o de força major. Els canvis es comunicaran per aquest web i, si cal, per correu electrònic a les persones inscrites.</p><h2>Continguts i propietat intel·lectual</h2><p>Els textos, les imatges, el disseny i la resta de continguts del web són de l\'{{entitat}} o s\'hi utilitzen amb permís, i no es poden reproduir amb finalitats comercials sense autorització. Podeu compartir lliurement els enllaços a les pàgines del web.</p><p>Si creieu que algun contingut vulnera els vostres drets, escriviu-nos a {{correu}} i el retirarem o el corregirem tan aviat com puguem.</p><h2>Enllaços i serveis d\'altri</h2><p>Algunes pàgines incorporen mapes de <em>Wikiloc</em> i d\'<em>OpenStreetMap</em>. Aquests mapes no es carreguen fins que hi feu clic: fins aleshores, el vostre navegador no es connecta a aquests serveis. El web també pot enllaçar a webs d\'altres entitats, col·laboradors o administracions, dels continguts dels quals no ens fem responsables.</p><h2>Disponibilitat</h2><p>Procurem que el web estigui sempre disponible i que la informació sigui correcta i actualitzada, però no podem garantir que no hi hagi interrupcions ni errades. Si en detecteu cap, agrairem que ens ho digueu.</p><h2>Legislació aplicable</h2><p>Aquestes condicions es regeixen per la legislació espanyola i catalana. Per a qualsevol qüestió relacionada amb el web, les parts se sotmeten als jutjats i tribunals que corresponguin per llei.</p>',
                'help' => 'Podeu escriure-hi {{entitat}}, {{cursa}}, {{poble}}, {{correu}}, {{telefon}} i {{web}}: en publicar-se, s\'hi posen les dades configurades. Si algun dia activeu el pagament en línia, reviseu el text: diu que no se\'n fa cap.'],
            'privacy_text' => ['label' => 'Política de privacitat', 'type' => 'html', 'rows' => 20, 'default' => '<h2>Qui és el responsable de les vostres dades</h2><p>El responsable del tractament és l\'<strong>{{entitat}}</strong>, associació sense ànim de lucre organitzadora del {{cursa}}, a {{poble}}. Per a qualsevol qüestió sobre les vostres dades podeu escriure\'ns a {{correu}}.</p><h2>Quines dades recollim i per què</h2><p><strong>Inscripció a la cursa.</strong> Nom i cognoms de la persona participant, any de naixement, gènere (opcional), escola o club (opcional), nom, correu electrònic i telèfon de la persona de contacte, i les observacions que hi vulgueu afegir. Les fem servir per organitzar la cursa: assignar la categoria i el número de dorsal, preparar les sortides, atendre qualsevol incidència el mateix dia i comunicar-vos-en els canvis. Amb aquestes dades us enviem el correu de confirmació de la inscripció.</p><p><strong>«Les meves inscripcions».</strong> Per deixar-vos consultar i modificar les vostres inscripcions us enviem un codi d\'un sol ús al correu electrònic que vau indicar. El codi caduca al cap de pocs minuts i no en desem el contingut, només una empremta xifrada que serveix per comprovar-lo.</p><p><strong>Formulari de contacte.</strong> Nom, correu electrònic i el missatge que ens escriviu, per poder-vos respondre. El missatge ens arriba per correu electrònic i no es desa al web.</p><p><strong>Tiquets del punt de recàrrega.</strong> Si en reserveu, hi consta el nom, el correu electrònic i, opcionalment, el telèfon de qui els demana, per preparar-los i lliurar-los. <strong>No hi ha cap pagament en línia:</strong> els tiquets es paguen presencialment i no recollim ni tractem cap dada bancària ni de targeta.</p><p><strong>Resultats de la cursa.</strong> Si es publiquen, hi surten el nom i els cognoms, el número de dorsal, la categoria, l\'escola o club i la posició de cada participant.</p><p><strong>Imatges.</strong> Durant la jornada es fan fotografies i vídeos de l\'activitat que podem publicar al web i als canals de l\'AFA i de l\'escola per difondre-la. Només ho fem si ho heu autoritzat expressament al formulari d\'inscripció, i podeu retirar l\'autorització quan vulgueu.</p><p><strong>Dades tècniques.</strong> El servidor desa registres d\'accés amb l\'adreça IP i la data, per seguretat i per detectar errades. El web utilitza una galeta pròpia de sessió, necessària per mantenir el formulari segur i, si escau, la sessió de «Les meves inscripcions».</p><h2>Amb quina base legal les tractem</h2><ul><li><strong>El vostre consentiment</strong>, que doneu en enviar el formulari d\'inscripció, de contacte o de tiquets, i en autoritzar l\'ús d\'imatges. El podeu retirar en qualsevol moment.</li><li><strong>L\'execució de la relació</strong> que neix de la inscripció: sense aquestes dades no us podem inscriure ni fer-vos arribar la informació de la cursa.</li><li><strong>L\'interès legítim</strong> de l\'entitat a garantir la seguretat del web i a deixar constància de la participació a l\'activitat.</li></ul><h2>Quant de temps les guardem</h2><p>Les dades d\'inscripció es conserven durant l\'edició en curs i les posteriors mentre siguin útils per organitzar la cursa i mantenir-ne l\'històric de participació, i com a màxim cinc anys, llevat que ens demaneu abans que les esborrem. Els missatges del formulari de contacte es conserven el temps necessari per respondre\'ls. Els codis d\'accés d\'un sol ús s\'esborren automàticament un cop caducats. Els resultats publicats i les fotografies poden quedar com a memòria històrica de l\'activitat mentre no en demaneu la retirada.</p><h2>A qui comuniquem les dades</h2><p>No venem ni cedim les vostres dades a ningú amb finalitats comercials. Només hi poden accedir:</p><ul><li>Les persones de l\'organització i del voluntariat que necessiten fer-ho per preparar la cursa.</li><li>L\'empresa que allotja el web i el servei de correu electrònic que fem servir per enviar-vos les confirmacions, que actuen com a encarregats del tractament i només poden tractar les dades seguint les nostres instruccions.</li><li>Les administracions públiques, quan una llei ho exigeixi.</li></ul><p>Els resultats i les imatges, quan es publiquen, són accessibles públicament al web.</p><h2>Quins drets teniu</h2><p>Podeu demanar-nos en qualsevol moment:</p><ul><li><strong>Accedir</strong> a les dades que tenim vostres.</li><li><strong>Rectificar-les</strong> si són errònies o han canviat. Les dades de la inscripció també les podeu corregir vosaltres mateixos des de «Les meves inscripcions».</li><li><strong>Suprimir-les</strong> quan ja no calguin per a la finalitat per la qual les vam recollir.</li><li><strong>Limitar-ne</strong> o <strong>oposar-vos</strong> al tractament, i demanar-ne la <strong>portabilitat</strong>.</li><li><strong>Retirar el consentiment</strong> que ens havíeu donat, sense que això afecti els tractaments fets abans de retirar-lo.</li></ul><p>Per exercir-los, escriviu-nos a {{correu}} indicant quin dret voleu exercir. Us respondrem tan aviat com puguem. Si considereu que no us hem atès correctament, podeu presentar una reclamació davant l\'Autoritat Catalana de Protecció de Dades (<a href="https://apdcat.gencat.cat" target="_blank" rel="noopener">apdcat.gencat.cat</a>).</p><h2>Dades de menors d\'edat</h2><p>Bona part de les persones participants són menors d\'edat. Les seves dades les facilita sempre el pare, la mare o qui en tingui la tutela legal, que és qui dona el consentiment en nom seu i qui pot exercir-ne els drets. No demanem als infants cap dada directament.</p><h2>Galetes i serveis externs</h2><p>El web utilitza una única galeta pròpia, tècnica i necessària, per mantenir la sessió i protegir els formularis. No fem servir galetes de publicitat ni de seguiment.</p><p>Les tipografies i la resta de recursos del web s\'allotgen al nostre propi servidor, de manera que navegar-hi no envia cap dada a tercers. Els mapes de Wikiloc i d\'OpenStreetMap només es carreguen si hi feu clic expressament; a partir d\'aquell moment, aquests serveis poden rebre la vostra adreça IP segons les seves pròpies polítiques.</p><h2>Seguretat</h2><p>Apliquem les mesures tècniques i organitzatives raonables per protegir les vostres dades: accés al panell de gestió amb contrasenya i registre d\'activitat, connexió xifrada i còpies de seguretat.</p><h2>Canvis en aquesta política</h2><p>Si canviem la manera com tractem les dades, actualitzarem aquest text i, si el canvi és rellevant, us ho farem saber. Us recomanem que hi doneu un cop d\'ull de tant en tant.</p>',
                'help' => 'Admet els mateixos marcadors que l\'avís legal. És un text de partida redactat segons el que recull aquest web: reviseu-lo i adapteu-lo a com treballeu, i si activeu el pagament en línia o afegiu serveis externs, actualitzeu-lo.'],
        ],
    ],

    'updates' => [
        'title' => 'Actualitzacions',
        'icon' => 'refresh',
        'description' => 'Origen de les actualitzacions automàtiques (OTA).',
        'admin_only' => true,
        'fields' => [
            'update_manifest_url' => ['label' => 'URL del manifest', 'type' => 'url', 'default' => 'https://api.github.com/repos/soportic-orb/crosescolar/releases/latest', 'help' => 'Admet el format propi (manifest.json) i l\'API de versions de GitHub.'],
            'update_token' => ['label' => 'Token d\'accés', 'type' => 'password', 'secret' => true, 'default' => '', 'help' => 'Només cal per a dipòsits privats.'],
            'update_auto_check' => ['label' => 'Comprovar automàticament', 'type' => 'bool', 'default' => '1'],
            'update_backup' => ['label' => 'Fer còpia de seguretat abans d\'actualitzar', 'type' => 'bool', 'default' => '1'],
        ],
    ],
];
